# Generated by Django 5.2.3 on 2026-07-03 23:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # noqa: RUF012
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name_en", models.CharField(max_length=200, verbose_name="Name (English)")),
                ("name_fr", models.CharField(max_length=200, verbose_name="Name (French)")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable identifier. Used in service-layer lookups. Example: 'service-request-evidence'",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "security_classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "Unclassified"),
                            ("protected_a", "Protected A"),
                            ("protected_b", "Protected B"),
                        ],
                        default="protected_b",
                        help_text="TBS SPIN 2023: aggregated citizen service delivery data defaults to Protected B. Lowering to Protected A requires Privacy Officer approval.",
                        max_length=20,
                        verbose_name="Security classification",
                    ),
                ),
                (
                    "allowed_mime_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON list of allowed MIME types for uploads in this category. Empty list means use the global CIVICOS["ALLOWED_UPLOAD_MIME_TYPES"] setting.',
                        verbose_name="Allowed MIME types",
                    ),
                ),
                (
                    "max_size_bytes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Maximum upload size in bytes for this category. 0 means use the global CIVICOS["MAX_UPLOAD_SIZE"] setting.',
                        verbose_name="Max file size (bytes)",
                    ),
                ),
                (
                    "min_retention_days",
                    models.PositiveIntegerField(
                        default=730,
                        help_text="Minimum days to retain after last administrative use. Privacy Act s.6(1) mandates at least 2 years (730 days) for administrative purpose records.",
                        verbose_name="Minimum retention (days)",
                    ),
                ),
                (
                    "max_retention_days",
                    models.PositiveIntegerField(
                        default=2555,
                        help_text="Maximum days to retain. After this, the document is scheduled for disposal unless a legal hold is active.",
                        verbose_name="Maximum retention (days)",
                    ),
                ),
                (
                    "is_transitory",
                    models.BooleanField(
                        default=False,
                        help_text="If True, documents in this category are destroyed once their purpose is fulfilled, regardless of min_retention_days — unless a legal hold is active. Ref: LAC Disposition Authorization #2016/001.",
                        verbose_name="Transitory record",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document category",
                "verbose_name_plural": "Document categories",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "original_filename",
                    models.CharField(
                        help_text="User-supplied filename. Never used as the storage path. PIPEDA: never write this value to audit event_detail.",
                        max_length=255,
                        verbose_name="Original filename",
                    ),
                ),
                (
                    "_storage_key",
                    models.CharField(
                        db_column="storage_key",
                        help_text="Internal S3/filesystem path. NEVER expose in templates, serializers, admin, API responses, or log messages. Access via service layer only.",
                        max_length=500,
                        verbose_name="Storage key",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="Validated magic-byte result — not the client-supplied Content-Type header.",
                        max_length=100,
                        verbose_name="MIME type",
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(verbose_name="File size (bytes)")),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending upload"),
                            ("scanning", "Scanning"),
                            ("active", "Active"),
                            ("quarantined", "Quarantined — Infected"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending_upload",
                        max_length=20,
                        verbose_name="Scan status",
                    ),
                ),
                (
                    "scan_completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Scan completed at"),
                ),
                (
                    "scan_engine_result",
                    models.TextField(
                        blank=True,
                        help_text="Raw result string from ClamAV (e.g. 'OK' or 'FOUND: Eicar-Test-Signature'). Stored for forensics; NEVER displayed to citizens.",
                        verbose_name="Scan engine result",
                    ),
                ),
                (
                    "security_classification",
                    models.CharField(
                        choices=[
                            ("unclassified", "Unclassified"),
                            ("protected_a", "Protected A"),
                            ("protected_b", "Protected B"),
                        ],
                        default="protected_b",
                        help_text="Inherits from category at creation. Overridable per-document by authorised admin only. Citizens cannot see or change this.",
                        max_length=20,
                        verbose_name="Security classification",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Version number"),
                ),
                (
                    "is_latest_version",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Exactly one Document per root chain must have this set to True. Managed exclusively by DocumentService.create_new_version().",
                        verbose_name="Is latest version",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this document is eligible for disposal (max retention exceeded). Null = does not expire (e.g. legal hold or manual override).",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "retain_until",
                    models.DateField(
                        blank=True,
                        help_text="Earliest date on which disposal is permitted. Set to max(created_at + min_retention_days, last_admin_use_at + 730 days). Updated whenever the document is used for an administrative purpose. Privacy Act s.6(1).",
                        null=True,
                        verbose_name="Retain until",
                    ),
                ),
                (
                    "last_admin_use_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last timestamp this document was used for an administrative purpose (e.g. referenced in a staff decision). Drives retain_until calculation.",
                        null=True,
                        verbose_name="Last administrative use at",
                    ),
                ),
                (
                    "legal_hold",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If True, this document is exempt from all scheduled disposal. Set only by Privacy Officer or legal counsel (requires documents.manage_legal_hold permission). Ref: TBS guidance on ATIP and litigation holds.",
                        verbose_name="Legal hold",
                    ),
                ),
                (
                    "legal_hold_reason",
                    models.TextField(
                        blank=True,
                        help_text="Non-PII description of why the hold was applied. Staff-internal only.",
                        verbose_name="Legal hold reason",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Staff-provided reason for deletion. Never exposed to citizens.",
                        verbose_name="Deletion reason",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Staff or citizen description of what this document contains. Must not contain sensitive PII — PII lives in the referenced records.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "legal_hold_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_hold_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Legal hold set by",
                    ),
                ),
                (
                    "root_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="FK to version 1 of this document chain. Null if and only if this document IS version 1.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="Root document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.documents.models._generate_token,
                        help_text="Opaque 64-char hex token. Single-use; invalidated on first use.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="Expires at")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on first (and only) use. Null means token has not been consumed.",
                        null=True,
                        verbose_name="Used at",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Masked IP address at token issuance. Last octet zeroed for IPv4.",
                        null=True,
                        verbose_name="IP address (masked)",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Issued to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document access token",
                "verbose_name_plural": "Document access tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "object_id",
                    models.CharField(
                        help_text="Supports UUID (36 chars) and integer PKs.",
                        max_length=50,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "attachment_role",
                    models.CharField(
                        default="supporting_evidence",
                        help_text="Role of this document on the linked object. Examples: 'supporting_evidence', 'decision_letter', 'volunteer_certification', 'cra_t4a_slip'.",
                        max_length=50,
                        verbose_name="Attachment role",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional staff note about why this document was attached. Not visible to citizens.",
                        verbose_name="Note",
                    ),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attached by",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document attachment",
                "verbose_name_plural": "Document attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="docattach_ct_obj_idx"),
                    models.Index(fields=["document", "content_type"], name="docattach_doc_ct_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["scan_status", "deleted_at"], name="doc_scan_deleted_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["expires_at", "legal_hold", "deleted_at"], name="doc_expiry_hold_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by", "created_at"], name="doc_uploader_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["root_document", "is_latest_version"], name="doc_root_latest_idx"
            ),
        ),
    ]
