# Generated by Django 5.2.3 on 2026-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("documents", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="documentcategory",
            name="staff_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, only users with the documents.upload_staff_document permission (or superusers) may upload to this category. Authenticated citizens are blocked even if they have documents.upload_document. Use for sensitive internal categories such as compliance reports or internal audit evidence.",
                verbose_name="Staff only",
            ),
        ),
    ]
