# Generated by Django 5.2.3 on 2026-07-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("documents", "0002_staff_only_flag"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("upload_document", "Can upload documents to public categories"),
                    ("upload_staff_document", "Can upload documents to staff-only categories"),
                ],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
