# Generated by Django 5.2.3 on 2026-06-29 00:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # noqa: RUF012
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "service_page_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Reference to the CMS ServicePage that initiated this request.",
                        null=True,
                        verbose_name="Service page ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Snapshot of service name at time of submission.",
                        max_length=255,
                        verbose_name="Service name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("awaiting_info", "Awaiting information"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=20, unique=True, verbose_name="Reference number"),
                ),
                ("submission_data", models.JSONField(default=dict, verbose_name="Submission data")),
                ("internal_notes", models.TextField(blank=True, verbose_name="Internal notes")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires at"
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Citizen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service request",
                "verbose_name_plural": "Service requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("awaiting_info", "Awaiting information"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        max_length=32,
                        verbose_name="Previous status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("awaiting_info", "Awaiting information"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        max_length=32,
                        verbose_name="New status",
                    ),
                ),
                (
                    "public_note",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the citizen in their portal. Keep plain and non-technical.",
                        verbose_name="Public note",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="portal.servicerequest",
                        verbose_name="Service request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status update",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["citizen", "status"], name="portal_serv_citizen_1c3b21_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["reference_number"], name="portal_serv_referen_f943b5_idx"),
        ),
    ]
