# Generated by Django 5.2.3 on 2026-06-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='old_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('awaiting_info', 'Awaiting information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=32, verbose_name='Previous status'),
        ),
    ]
