# Generated by Django 5.2.3 on 2026-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("portal", "0002_alter_statusupdate_old_status"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="servicerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_name",
            field=models.CharField(
                db_index=True,
                help_text="Snapshot of service name at time of submission.",
                max_length=255,
                verbose_name="Service name",
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
    ]
