# Generated by hand — Wave 1 Round 1 (Payments BB data model layer)
# All field definitions match models.py exactly, including help_text.
import decimal
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class ConditionalRunSQL(migrations.RunSQL):
    """RunSQL that only executes on PostgreSQL, skips on SQLite (for tests)."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state) -> None:  # noqa: ANN001
        engine = schema_editor.connection.settings_dict.get("ENGINE", "")
        if "postgresql" in engine or "postgis" in engine:
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state) -> None:  # noqa: ANN001
        engine = schema_editor.connection.settings_dict.get("ENGINE", "")
        if "postgresql" in engine or "postgis" in engine:
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # noqa: RUF012
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        # ------------------------------------------------------------------
        # TenantPaymentConfig
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="TenantPaymentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "use_connect",
                    models.BooleanField(
                        default=False,
                        verbose_name="Use Stripe Connect",
                        help_text="True = Stripe Connect multi-tenant mode.",
                    ),
                ),
                (
                    "stripe_publishable_key",
                    models.CharField(
                        max_length=255, blank=True, verbose_name="Stripe Publishable Key"
                    ),
                ),
                (
                    "stripe_connect_account_id",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Stripe Connect Account ID",
                        help_text="Stripe platform account ID (Connect mode).",
                    ),
                ),
                (
                    "webhook_endpoint_secret",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Webhook Endpoint Secret",
                        help_text=(
                            "Changing this requires rotating the Stripe webhook signing secret "
                            "and redeploying."
                        ),
                    ),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(
                        default=True,
                        verbose_name="Test Mode",
                        help_text="Use Stripe test keys. Must be False in production.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Payment Config",
                "verbose_name_plural": "Tenant Payment Config",
            },
        ),
        # ------------------------------------------------------------------
        # CharitySettings
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="CharitySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "charity_legal_name",
                    models.CharField(max_length=255, verbose_name="Charity Legal Name"),
                ),
                (
                    "charity_registration_number",
                    models.CharField(
                        max_length=20,
                        verbose_name="CRA Registration Number",
                        help_text="Format: 123456789 RR 0001",
                        validators=[
                            django.core.validators.RegexValidator(
                                r"^\d{9} RR \d{4}$",
                                "Must match CRA format: 123456789 RR 0001",
                            )
                        ],
                    ),
                ),
                (
                    "charity_address_line1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "charity_city",
                    models.CharField(max_length=100, verbose_name="City"),
                ),
                (
                    "charity_province",
                    models.CharField(
                        max_length=2,
                        verbose_name="Province",
                        help_text="ISO 3166-2 province code (e.g. ON, QC).",
                    ),
                ),
                (
                    "charity_postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                (
                    "place_of_issue",
                    models.CharField(
                        max_length=100,
                        verbose_name="Place of Issue",
                        help_text="City where receipts are issued (CRA requirement).",
                    ),
                ),
                (
                    "authorized_signatory_name",
                    models.CharField(max_length=255, verbose_name="Authorized Signatory Name"),
                ),
                (
                    "authorized_signatory_title",
                    models.CharField(max_length=255, verbose_name="Authorized Signatory Title"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, blank=True, verbose_name="Display Name (English)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=255, blank=True, verbose_name="Display Name (French)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Charity Settings",
                "verbose_name_plural": "Charity Settings",
            },
        ),
        # ------------------------------------------------------------------
        # FeeSchedule
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "service_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Service Type",
                        help_text="Matches service request service_type slug.",
                    ),
                ),
                (
                    "fee_code",
                    models.CharField(max_length=50, verbose_name="Fee Code"),
                ),
                (
                    "amount",
                    models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount"),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=False, verbose_name="Is Taxable"),
                ),
                (
                    "province",
                    models.CharField(
                        max_length=2,
                        verbose_name="Province",
                        help_text="ISO 3166-2 province code.",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(max_length=255, verbose_name="Description (English)"),
                ),
                (
                    "description_fr",
                    models.CharField(
                        max_length=255, blank=True, verbose_name="Description (French)"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "expiry_date",
                    models.DateField(null=True, blank=True, verbose_name="Expiry Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Fee Schedule",
                "verbose_name_plural": "Fee Schedules",
                "ordering": ["fee_code", "-effective_date"],
            },
        ),
        # ------------------------------------------------------------------
        # TaxRate
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "province",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        verbose_name="Province",
                        help_text="ISO 3166-2 province/territory code.",
                    ),
                ),
                (
                    "federal_rate",
                    models.DecimalField(
                        max_digits=7,
                        decimal_places=5,
                        verbose_name="Federal Rate",
                        help_text="e.g. 0.0500 for 5% GST.",
                    ),
                ),
                (
                    "provincial_rate",
                    models.DecimalField(
                        max_digits=7,
                        decimal_places=5,
                        verbose_name="Provincial Rate",
                        help_text="e.g. 0.0800 for 8% PST.",
                    ),
                ),
                (
                    "combined_rate",
                    models.DecimalField(
                        max_digits=7,
                        decimal_places=5,
                        verbose_name="Combined Rate",
                        help_text="Total tax rate applied to taxable fees.",
                    ),
                ),
                (
                    "tax_name_en",
                    models.CharField(
                        max_length=50,
                        verbose_name="Tax Name (English)",
                        help_text="e.g. 'HST', 'GST + PST'.",
                    ),
                ),
                (
                    "tax_name_fr",
                    models.CharField(max_length=50, verbose_name="Tax Name (French)"),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["province"],
            },
        ),
        # ------------------------------------------------------------------
        # DonationCampaign
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Name (English)"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, blank=True, verbose_name="Name (French)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (French)"),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        null=True,
                        blank=True,
                        verbose_name="Goal Amount",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(null=True, blank=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "advantage_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Default Advantage Amount",
                        help_text=(
                            "Default advantage amount for donations to this campaign "
                            "(FMV of benefit received by donor). OQ-8."
                        ),
                    ),
                ),
                (
                    "advantage_description_en",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Advantage Description (English)",
                    ),
                ),
                (
                    "advantage_description_fr",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Advantage Description (French)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation Campaign",
                "verbose_name_plural": "Donation Campaigns",
                "ordering": ["sort_order", "name_en"],
            },
        ),
        # ------------------------------------------------------------------
        # PaymentIntent
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        blank=True,
                        help_text="Human-readable reference: PMT-YYYY-NNNNNN. Auto-generated on save.",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        verbose_name="Payer",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=3, default="CAD", verbose_name="Currency"),
                ),
                (
                    "purpose",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("service_fee", "Service Fee"),
                            ("donation", "Donation"),
                            ("fine", "Fine / Penalty"),
                        ],
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        db_index=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        max_length=20,
                        choices=[("stripe", "Stripe"), ("moneris", "Moneris")],
                        default="stripe",
                        verbose_name="Payment Gateway",
                    ),
                ),
                (
                    "gateway_intent_id",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Gateway Intent ID",
                        help_text=(
                            "ID returned by the payment gateway " "(e.g. Stripe PaymentIntent ID)."
                        ),
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        unique=True,
                        default=uuid.uuid4,
                        verbose_name="Idempotency Key",
                        help_text="Prevents duplicate charges on retry.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        blank=True,
                        verbose_name="Metadata",
                        help_text="Arbitrary key-value data for gateway or app context.",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(max_length=500, blank=True, verbose_name="Failure Reason"),
                ),
            ],
            options={
                "verbose_name": "Payment Intent",
                "verbose_name_plural": "Payment Intents",
                "ordering": ["-created_at"],
            },
        ),
        # ------------------------------------------------------------------
        # Payment
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "intent",
                    models.OneToOneField(
                        to="payments.PaymentIntent",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        verbose_name="Payment Intent",
                    ),
                ),
                (
                    "gateway_charge_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Gateway Charge ID",
                        help_text="Charge/transaction ID returned by the gateway.",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        max_digits=10, decimal_places=2, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "processor_fee",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Processor Fee",
                        help_text="Gateway processing fee deducted from gross amount.",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        verbose_name="Net Amount",
                        help_text="Amount after processor fee: amount_paid - processor_fee.",
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        max_length=20,
                        choices=[("card", "Card"), ("bank_transfer", "Bank Transfer")],
                        verbose_name="Payment Method Type",
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        max_length=4,
                        blank=True,
                        null=True,
                        verbose_name="Card Last Four",
                        help_text="Last 4 digits of the card used. Never store full PAN.",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        max_length=20,
                        blank=True,
                        null=True,
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "Amex"),
                            ("interac", "Interac"),
                            ("other", "Other"),
                        ],
                        verbose_name="Card Brand",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(db_index=True, verbose_name="Paid At"),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-paid_at"],
            },
        ),
        # ------------------------------------------------------------------
        # Refund
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        to="payments.Payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        max_digits=10, decimal_places=2, verbose_name="Refund Amount"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("fraudulent", "Fraudulent"),
                            ("requested_by_customer", "Requested by Customer"),
                            ("service_not_rendered", "Service Not Rendered"),
                        ],
                        verbose_name="Reason",
                    ),
                ),
                (
                    "gateway_refund_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Gateway Refund ID",
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(db_index=True, verbose_name="Refunded At"),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_refunds",
                        verbose_name="Authorized By",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "ordering": ["-refunded_at"],
            },
        ),
        # ------------------------------------------------------------------
        # WebhookEvent
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "gateway",
                    models.CharField(
                        max_length=20,
                        choices=[("stripe", "Stripe"), ("moneris", "Moneris")],
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Event Type",
                        help_text="e.g. payment_intent.succeeded",
                    ),
                ),
                (
                    "gateway_event_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Gateway Event ID",
                        help_text=("Idempotency key from gateway — prevents double-processing."),
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        verbose_name="Payload",
                        help_text="Full event payload as received from gateway.",
                    ),
                ),
                (
                    "signature_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Signature Verified",
                        help_text=(
                            "Only process events where signature has been "
                            "cryptographically verified."
                        ),
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, db_index=True, verbose_name="Processed"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(null=True, blank=True, verbose_name="Processed At"),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        verbose_name="Error",
                        help_text="Last processing error, if any.",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Retry Count"),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-created_at"],
            },
        ),
        # ------------------------------------------------------------------
        # PaymentAuditEntry
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="PaymentAuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="payment_audit_entries",
                        verbose_name="Actor",
                        help_text="Staff or citizen who triggered the action, if applicable.",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("intent_created", "Intent Created"),
                            ("intent_processing", "Intent Processing"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_cancelled", "Payment Cancelled"),
                            ("refund_requested", "Refund Requested"),
                            ("refund_completed", "Refund Completed"),
                            ("refund_failed", "Refund Failed"),
                            ("donation_created", "Donation Created"),
                            ("receipt_issued", "Receipt Issued"),
                            ("receipt_cancelled", "Receipt Cancelled"),
                            ("receipt_superseded", "Receipt Superseded"),
                            ("recurring_plan_created", "Recurring Plan Created"),
                            ("recurring_plan_paused", "Recurring Plan Paused"),
                            ("recurring_plan_cancelled", "Recurring Plan Cancelled"),
                            ("webhook_received", "Webhook Received"),
                            ("webhook_processed", "Webhook Processed"),
                            ("webhook_failed", "Webhook Failed"),
                        ],
                        db_index=True,
                        verbose_name="Action",
                    ),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        to="payments.PaymentIntent",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="audit_entries",
                        verbose_name="Payment Intent",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        to="payments.Payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="audit_entries",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        to="payments.Refund",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="audit_entries",
                        verbose_name="Refund",
                    ),
                ),
                (
                    "actor_ip",
                    models.CharField(
                        max_length=45,
                        blank=True,
                        verbose_name="Actor IP",
                        help_text="Always masked before storage. Never log full IP with PII.",
                    ),
                ),
                (
                    "details",
                    models.JSONField(default=dict, blank=True, verbose_name="Details"),
                ),
            ],
            options={
                "verbose_name": "Payment Audit Entry",
                "verbose_name_plural": "Payment Audit Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentauditentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    action__in=[
                        "intent_created",
                        "intent_processing",
                        "payment_completed",
                        "payment_failed",
                        "payment_cancelled",
                        "refund_requested",
                        "refund_completed",
                        "refund_failed",
                        "donation_created",
                        "receipt_issued",
                        "receipt_cancelled",
                        "receipt_superseded",
                        "recurring_plan_created",
                        "recurring_plan_paused",
                        "recurring_plan_cancelled",
                        "webhook_received",
                        "webhook_processed",
                        "webhook_failed",
                    ]
                ),
                name="payments_audit_action_valid",
            ),
        ),
        # ------------------------------------------------------------------
        # ServiceFeePayment
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="ServiceFeePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "payment_intent",
                    models.OneToOneField(
                        to="payments.PaymentIntent",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_fee_payment",
                        verbose_name="Payment Intent",
                    ),
                ),
                (
                    "service_request_id",
                    models.UUIDField(
                        verbose_name="Service Request ID",
                        help_text=("Portal ServiceRequest PK — no FK to avoid cross-app coupling."),
                    ),
                ),
                (
                    "fee_code",
                    models.CharField(
                        max_length=50,
                        verbose_name="Fee Code",
                        help_text="Snapshot of FeeSchedule.fee_code at time of payment.",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        max_digits=10, decimal_places=2, verbose_name="Base Amount"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "tax_rate_applied",
                    models.DecimalField(
                        max_digits=7,
                        decimal_places=5,
                        default=decimal.Decimal("0.00000"),
                        verbose_name="Tax Rate Applied",
                        help_text="Snapshot of TaxRate.combined_rate at time of payment.",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        max_length=255,
                        verbose_name="Description (English)",
                        help_text="Snapshot of fee description (EN).",
                    ),
                ),
                (
                    "description_fr",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Description (French)",
                        help_text="Snapshot of fee description (FR).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Fee Payment",
                "verbose_name_plural": "Service Fee Payments",
            },
        ),
        # ------------------------------------------------------------------
        # RecurringGiftPlan
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="RecurringGiftPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_plans",
                        verbose_name="Donor",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        to="payments.DonationCampaign",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="recurring_plans",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        verbose_name="Amount per Period",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "next_charge_date",
                    models.DateField(verbose_name="Next Charge Date"),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Gateway Subscription ID",
                    ),
                ),
                (
                    "gateway_payment_method_id",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Gateway Payment Method ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        db_index=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(null=True, blank=True, verbose_name="Cancelled At"),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        max_length=500, blank=True, verbose_name="Cancellation Reason"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Gift Plan",
                "verbose_name_plural": "Recurring Gift Plans",
                "ordering": ["-created_at"],
            },
        ),
        # ------------------------------------------------------------------
        # Donation
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "payment_intent",
                    models.ForeignKey(
                        to="payments.PaymentIntent",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        verbose_name="Payment Intent",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        verbose_name="Donor",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        to="payments.DonationCampaign",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="donations",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        verbose_name="Donation Amount",
                    ),
                ),
                (
                    "advantage_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Advantage Amount",
                        help_text=(
                            "FMV of benefit received by donor (OQ-8). "
                            "Reduces eligible tax credit."
                        ),
                    ),
                ),
                (
                    "advantage_description",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Advantage Description",
                    ),
                ),
                (
                    "eligible_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        verbose_name="Eligible Amount",
                        help_text="amount - advantage_amount. Computed and stored on save().",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Is Recurring"),
                ),
                (
                    "recurring_plan",
                    models.ForeignKey(
                        to="payments.RecurringGiftPlan",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="donations",
                        verbose_name="Recurring Plan",
                    ),
                ),
                (
                    "dedication_type",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("in_memory_of", "In Memory Of"),
                            ("in_honour_of", "In Honour Of"),
                        ],
                        null=True,
                        blank=True,
                        verbose_name="Dedication Type",
                    ),
                ),
                (
                    "dedication_name",
                    models.CharField(max_length=255, blank=True, verbose_name="Dedication Name"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Is Anonymous"),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        db_index=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "donor_name_snapshot",
                    models.CharField(
                        max_length=255,
                        verbose_name="Donor Legal Name (Snapshot)",
                        help_text="Legal name at time of donation — CRA requirement.",
                    ),
                ),
                (
                    "donor_address_snapshot",
                    models.TextField(
                        verbose_name="Donor Address (Snapshot)",
                        help_text="Full mailing address at time of donation — CRA requirement.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "ordering": ["-created_at"],
            },
        ),
        # ------------------------------------------------------------------
        # OfficialDonationReceipt
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="OfficialDonationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        to="payments.Donation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        verbose_name="Donation",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Serial Number",
                        help_text=(
                            "YYYY-NNNNNN format, generated from DB sequence "
                            "payments_receipt_serial_seq."
                        ),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("issued", "Issued"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Superseded"),
                        ],
                        default="issued",
                        db_index=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        to="payments.OfficialDonationReceipt",
                        on_delete=django.db.models.deletion.PROTECT,
                        null=True,
                        blank=True,
                        related_name="supersedes",
                        verbose_name="Superseded By",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        max_length=500,
                        blank=True,
                        verbose_name="Cancellation Reason",
                    ),
                ),
                (
                    "donor_legal_name",
                    models.CharField(max_length=255, verbose_name="Donor Legal Name"),
                ),
                (
                    "donor_address_line1",
                    models.CharField(max_length=255, verbose_name="Donor Address Line 1"),
                ),
                (
                    "donor_city",
                    models.CharField(max_length=100, verbose_name="Donor City"),
                ),
                (
                    "donor_province",
                    models.CharField(max_length=2, verbose_name="Donor Province"),
                ),
                (
                    "donor_postal_code",
                    models.CharField(max_length=10, verbose_name="Donor Postal Code"),
                ),
                ("donation_date", models.DateField(verbose_name="Donation Date")),
                ("receipt_date", models.DateField(verbose_name="Receipt Date")),
                (
                    "eligible_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        verbose_name="Eligible Amount",
                    ),
                ),
                (
                    "advantage_amount",
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        verbose_name="Advantage Amount",
                    ),
                ),
                (
                    "advantage_description",
                    models.CharField(
                        max_length=255,
                        blank=True,
                        verbose_name="Advantage Description",
                    ),
                ),
                (
                    "charity_legal_name",
                    models.CharField(max_length=255, verbose_name="Charity Legal Name"),
                ),
                (
                    "charity_registration_number",
                    models.CharField(max_length=20, verbose_name="CRA Registration Number"),
                ),
                (
                    "charity_address",
                    models.TextField(verbose_name="Charity Address"),
                ),
                (
                    "place_of_issue",
                    models.CharField(max_length=100, verbose_name="Place of Issue"),
                ),
                (
                    "authorized_signatory_name",
                    models.CharField(max_length=255, verbose_name="Authorized Signatory Name"),
                ),
                (
                    "authorized_signatory_title",
                    models.CharField(max_length=255, verbose_name="Authorized Signatory Title"),
                ),
                (
                    "pdf_path",
                    models.CharField(
                        max_length=500,
                        blank=True,
                        verbose_name="PDF Path",
                        help_text=(
                            "Internal storage path — NEVER expose in API, "
                            "templates, or admin list_display."
                        ),
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Issued At",
                    ),
                ),
                (
                    "is_annual_consolidated",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is Annual Consolidated",
                        help_text=(
                            "True for year-end consolidated receipts that "
                            "supersede monthly receipts."
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": "Official Donation Receipt",
                "verbose_name_plural": "Official Donation Receipts",
                "ordering": ["-issued_at"],
            },
        ),
        # ------------------------------------------------------------------
        # Constraints — FeeSchedule (FIX 1, FIX 18)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.UniqueConstraint(
                fields=["fee_code", "province", "effective_date"],
                name="payments_feeschedule_code_province_date_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gte=0),
                name="payments_feeschedule_amount_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeschedule",
            constraint=models.CheckConstraint(
                check=models.Q(expiry_date__isnull=True)
                | models.Q(expiry_date__gt=models.F("effective_date")),
                name="payments_feeschedule_dates_valid",
            ),
        ),
        # ------------------------------------------------------------------
        # Constraints — PaymentIntent (FIX 2)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gt=0),
                name="payments_intent_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.CheckConstraint(
                check=models.Q(tax_amount__gte=0),
                name="payments_intent_tax_nonneg",
            ),
        ),
        # ------------------------------------------------------------------
        # Indexes — PaymentIntent (FIX 11)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["payer", "status"], name="payments_intent_payer_status"),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["status"], name="payments_intent_status"),
        ),
        # ------------------------------------------------------------------
        # Constraints — Refund (FIX 17)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gt=0),
                name="payments_refund_amount_positive",
            ),
        ),
        # ------------------------------------------------------------------
        # Indexes — WebhookEvent (FIX 11)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["processed", "gateway"], name="payments_webhook_proc_gw"),
        ),
        # ------------------------------------------------------------------
        # Indexes — PaymentAuditEntry (FIX 11, FIX 14)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="paymentauditentry",
            index=models.Index(fields=["payment_intent"], name="payments_audit_intent"),
        ),
        migrations.AddIndex(
            model_name="paymentauditentry",
            index=models.Index(fields=["created_at"], name="payments_audit_timestamp"),
        ),
        # ------------------------------------------------------------------
        # Constraints — CharitySettings (FIX 8)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="charitysettings",
            constraint=models.UniqueConstraint(
                fields=["is_active"],
                condition=models.Q(is_active=True),
                name="payments_charitysettings_one_active",
            ),
        ),
        # ------------------------------------------------------------------
        # Indexes — RecurringGiftPlan (FIX 11)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="recurringgiftplan",
            index=models.Index(fields=["donor", "status"], name="payments_plan_donor_status"),
        ),
        migrations.AddIndex(
            model_name="recurringgiftplan",
            index=models.Index(
                fields=["next_charge_date", "status"], name="payments_plan_charge_date_st"
            ),
        ),
        # ------------------------------------------------------------------
        # Constraints — Donation (FIX 2, FIX 13)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                check=models.Q(amount__gt=0),
                name="payments_donation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                check=models.Q(eligible_amount__gte=0),
                name="payments_donation_eligible_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                check=models.Q(advantage_amount__lte=models.F("amount")),
                name="payments_donation_advantage_lte_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                check=~models.Q(donor_name_snapshot=""),
                name="payments_donation_donor_name_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="donation",
            constraint=models.CheckConstraint(
                check=~models.Q(donor_address_snapshot=""),
                name="payments_donation_donor_address_required",
            ),
        ),
        # ------------------------------------------------------------------
        # Indexes — Donation (FIX 11)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor"], name="payments_donation_donor"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["campaign", "status"], name="payments_donation_camp_status"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["status"], name="payments_donation_status"),
        ),
        # ------------------------------------------------------------------
        # Constraints — OfficialDonationReceipt (FIX 12)
        # ------------------------------------------------------------------
        migrations.AddConstraint(
            model_name="officialdonationreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(eligible_amount__gte=0),
                name="payments_receipt_eligible_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialdonationreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(advantage_amount__gte=0),
                name="payments_receipt_advantage_nonneg",
            ),
        ),
        # ------------------------------------------------------------------
        # Indexes — OfficialDonationReceipt (FIX 11)
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name="officialdonationreceipt",
            index=models.Index(fields=["donation", "status"], name="payments_receipt_don_status"),
        ),
        migrations.AddIndex(
            model_name="officialdonationreceipt",
            index=models.Index(
                fields=["is_annual_consolidated", "receipt_date"],
                name="payments_receipt_annual_date",
            ),
        ),
        # ------------------------------------------------------------------
        # PostgreSQL sequence for receipt serial numbers.
        # Skipped automatically on SQLite (test/CI environments).
        # Must be after all CreateModel operations.
        # ------------------------------------------------------------------
        ConditionalRunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS payments_receipt_serial_seq START WITH 1 INCREMENT BY 1 NO CYCLE;",
            reverse_sql="DROP SEQUENCE IF EXISTS payments_receipt_serial_seq;",
        ),
    ]
