# Generated by Django 5.2.3 on 2026-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_gateway_intent_id_index_and_event_type_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='officialdonationreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'issued')), fields=('donation',), name='payments_receipt_unique_issued_per_donation'),
        ),
    ]
