# Generated by Django 5.2.3 on 2026-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_receipt_amount_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'Amex'), ('interac', 'Interac'), ('discover', 'Discover'), ('jcb', 'JCB'), ('diners', 'Diners Club'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20, null=True, verbose_name='Card Brand'),
        ),
    ]
