# Generated by Django 5.2.3 on 2026-07-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_manual_gateway_and_honorarium_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('moneris', 'Moneris'), ('manual', 'Manual / Offline')], max_length=20, verbose_name='Gateway'),
        ),
    ]
