# Generated by Django 5.2.3 on 2026-07-20 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("payments", "0016_govstack_models"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="bulkpaymentbatch",
            options={
                "verbose_name": "Bulk Payment Batch",
                "verbose_name_plural": "Bulk Payment Batches",
            },
        ),
        migrations.AlterModelOptions(
            name="creditinstruction",
            options={
                "verbose_name": "Credit Instruction",
                "verbose_name_plural": "Credit Instructions",
            },
        ),
        migrations.AlterModelOptions(
            name="govstackbeneficiary",
            options={
                "verbose_name": "GovStack Beneficiary",
                "verbose_name_plural": "GovStack Beneficiaries",
            },
        ),
        migrations.AlterModelOptions(
            name="govstackvoucher",
            options={
                "verbose_name": "GovStack Voucher",
                "verbose_name_plural": "GovStack Vouchers",
            },
        ),
        migrations.AlterModelOptions(
            name="prepaymentvalidationrequest",
            options={
                "verbose_name": "Prepayment Validation Request",
                "verbose_name_plural": "Prepayment Validation Requests",
            },
        ),
        migrations.AlterField(
            model_name="bulkpaymentbatch",
            name="batch_id",
            field=models.CharField(
                help_text="BatchID from Source BB. Must be globally unique.",
                max_length=20,
                unique=True,
                verbose_name="Batch ID",
            ),
        ),
        migrations.AlterField(
            model_name="govstackbeneficiary",
            name="payee_functional_id",
            field=models.CharField(
                help_text="Government-assigned functional identity for this beneficiary. Must be 1–20 lowercase hex chars and hyphens per GovStack G2P spec. NEVER write to logs.",  # noqa: RUF001
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Payee Functional ID must be 1–20 lowercase hex characters and hyphens (e.g. '2ba5ed20-0f42-4eff-8'). Uppercase letters are not permitted.",  # noqa: RUF001
                        regex="^[0-9a-f\\-]{1,20}$",
                    )
                ],
                verbose_name="Payee Functional ID",
            ),
        ),
        migrations.AlterField(
            model_name="govstackvoucher",
            name="serial_number",
            field=models.CharField(
                help_text="Public voucher serial number. Assigned on pre-activation. Safe to expose in API responses.",
                max_length=20,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="prepaymentvalidationrequest",
            name="request_id",
            field=models.CharField(max_length=16, unique=True, verbose_name="Request ID"),
        ),
    ]
