# Generated by Django 5.2.3 on 2026-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("payments", "0018_tighten_govstackbeneficiary_source_bb_id_validator"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="bulkpaymentbatch",
            name="correlation_id",
            field=models.CharField(
                blank=True,
                help_text="X-CorrelationID header. Max 100 chars (accommodates UUIDs and longer IDs).",
                max_length=100,
                verbose_name="Correlation ID",
            ),
        ),
    ]
