# Generated by Django 5.2.3 on 2026-07-01 21:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("consent", "0003_protect_citizen_fk"),
        ("volunteers", "0004_h2_h4_h5_fixes"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="certification",
            name="cert_type_other",
            field=models.CharField(
                blank=True,
                help_text="Required when cert_type = 'other'.",
                max_length=100,
                verbose_name="Other certificate type",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Scanned certificate (PDF or image). Stored in private S3 bucket — not publicly accessible.",
                null=True,
                upload_to="volunteers/certifications/",
                verbose_name="Certificate document",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="expires_date",
            field=models.DateField(
                blank=True, help_text="Null = no expiry.", null=True, verbose_name="Expiry date"
            ),
        ),
        migrations.AlterField(
            model_name="honorarium",
            name="calendar_year",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.datetime.ExtractYear("payment_date"),
                help_text="Automatically derived from payment_date. Used for CRA threshold tracking.",
                output_field=models.PositiveSmallIntegerField(),
                verbose_name="Calendar year",
            ),
        ),
        migrations.AlterField(
            model_name="honorarium",
            name="t4a_required",
            field=models.BooleanField(
                default=False,
                help_text="True when volunteer's cumulative honoraria exceed $500 in this calendar_year.",
                verbose_name="T4A required",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="closes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Applications accepted until this date/time. Blank = no close date.",
                null=True,
                verbose_name="Closes at",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="honorarium_per_shift",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional nominal honorarium per approved shift. Subject to CRA $500/year threshold — see docs/volunteer-management-bb-spec.md §3.2.",
                max_digits=8,
                null=True,
                verbose_name="Honorarium per shift (CAD)",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="is_remote",
            field=models.BooleanField(
                default=False,
                help_text="Volunteers can participate from any location.",
                verbose_name="Remote / virtual",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="minimum_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leave blank for no age restriction.",
                null=True,
                verbose_name="Minimum age",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="required_profile_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of VolunteerProfile fields the application form will prompt for. Only include what the role actually requires (PIPEDA minimum-collection).",
                verbose_name="Required profile fields",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="requires_vulnerable_sector_check",
            field=models.BooleanField(
                default=False,
                help_text="Role involves unsupervised access to children or vulnerable adults. VSC must be obtained from local police detachment in person.",
                verbose_name="Requires Vulnerable Sector Check",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="volunteer_agreement",
            field=models.ForeignKey(
                blank=True,
                help_text="Consent category representing the volunteer agreement. Volunteers must accept this before their application is submitted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunity_agreements",
                to="consent.consentcategory",
                verbose_name="Volunteer agreement",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="volunteer_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Maximum concurrent active volunteers. Leave blank for unlimited.",
                null=True,
                verbose_name="Volunteer capacity",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="cra_category",
            field=models.CharField(
                choices=[
                    ("welfare", "Welfare of the general public"),
                    ("education", "Education"),
                    ("health", "Health"),
                    ("religion", "Religion"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="CRA charitable program category for T3010 reporting. Hours for this program contribute to the corresponding T3010 line.",
                max_length=20,
                verbose_name="CRA T3010 category",
            ),
        ),
        migrations.AlterField(
            model_name="screeningrecord",
            name="completed_date",
            field=models.DateField(
                help_text="Date the volunteer completed or obtained the check.",
                verbose_name="Completed date",
            ),
        ),
        migrations.AlterField(
            model_name="screeningrecord",
            name="expires_date",
            field=models.DateField(
                blank=True,
                help_text="VSC default = 3 years from completed_date. Null = no expiry (e.g. reference checks).",
                null=True,
                verbose_name="Expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="screeningrecord",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="⚠ PIPEDA / CRA constraint: record only the screening outcome date, check-type, and logistical notes (e.g. 'submitted to RCMP 2024-03-01'). Do NOT record criminal record details, offence descriptions, charge history, or any result beyond the verified_clear flag. Access to this field is audit-logged. Maximum 300 characters.",
                max_length=300,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AlterField(
            model_name="screeningrecord",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                help_text="Opportunity this check was obtained for. Null = general / organization-wide.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screening_records",
                to="volunteers.opportunity",
                verbose_name="Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="screeningrecord",
            name="verified_clear",
            field=models.BooleanField(
                blank=True,
                help_text="True = coordinator confirmed the result is clear. False = result not clear (triggers workflow). Null = not yet verified by coordinator. The actual criminal record detail is NEVER stored here.",
                null=True,
                verbose_name="Result: verified clear",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Max volunteers for this shift. Null = inherits Opportunity.volunteer_capacity.",
                null=True,
                verbose_name="Capacity",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="is_remote",
            field=models.BooleanField(
                blank=True,
                help_text="If set, overrides the Opportunity's remote flag for this shift only.",
                null=True,
                verbose_name="Remote override",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="location_override",
            field=models.CharField(
                blank=True,
                help_text="If set, overrides the Opportunity's location for this shift only.",
                max_length=300,
                verbose_name="Location override",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="waitlist_cap",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Max waitlist size. Null = unlimited.",
                null=True,
                verbose_name="Waitlist cap",
            ),
        ),
        migrations.AlterField(
            model_name="shiftbooking",
            name="waitlist_position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1 = next to be promoted. Null if confirmed.",
                null=True,
                verbose_name="Waitlist position",
            ),
        ),
        migrations.AlterField(
            model_name="skilltag",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="e.g. Technical, Language, Health, Administrative",
                max_length=50,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="consent_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Signed volunteer agreement via Consent BB.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volunteer_applications",
                to="consent.consentrecord",
                verbose_name="Consent record",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="motivation",
            field=models.TextField(
                blank=True,
                help_text="Volunteer's motivation / cover letter.",
                verbose_name="Motivation",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Internal coordinator notes. PIPEDA: never exposed to the volunteer — notification uses generic 'not selected' language only.",
                verbose_name="Rejection reason",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="screening_notes",
            field=models.TextField(
                blank=True,
                help_text="Coordinator-only notes about this applicant's screening status.",
                verbose_name="Screening notes",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="accommodation_notes",
            field=models.TextField(
                blank=True,
                help_text="Dietary, mobility, or other accessibility needs. Visible to authorized coordinators only.",
                verbose_name="Accommodation / access needs",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="availability_notes",
            field=models.TextField(
                blank=True,
                help_text="Free-text description of general availability.",
                verbose_name="Availability notes",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Only collected when the Opportunity requires age verification (Opportunity.required_profile_fields includes 'date_of_birth').",
                null=True,
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Requires photo_consent before upload.",
                null=True,
                upload_to="volunteers/photos/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="How the volunteer prefers to be addressed.",
                max_length=100,
                verbose_name="Preferred name",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="sin_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="Fernet-encrypted Social Insurance Number. Only collected when honorarium exceeds CRA $500 threshold. Never logged or displayed — use sin_last4 for confirmation.",
                null=True,
                verbose_name="SIN (encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="sin_last4",
            field=models.CharField(
                blank=True,
                help_text="Last 4 digits of SIN for display confirmation only.",
                max_length=4,
                verbose_name="SIN last 4 digits",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerprofile",
            name="total_hours_approved",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Denormalized sum of approved HoursLog rows. Authoritative source is HoursLog — recomputed on every approval.",
                max_digits=10,
                verbose_name="Total approved hours",
            ),
        ),
    ]
