# Generated by Django 5.2.3 on 2026-07-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_screening_verified_clear_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteernote',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='Note body'),
        ),
    ]
