"""
Celery tasks for donation receipt generation and delivery.

Security invariants:
- Donor emails NEVER logged.
- Donor names NEVER logged.
- Only serial_number, donation_pk, tax_year, and counts are logged.
"""
from __future__ import annotations

import itertools
import logging
from datetime import datetime
from decimal import Decimal
from operator import attrgetter

import pytz

from celery import shared_task
from django.conf import settings
from django.db import IntegrityError, transaction
from django.utils import timezone
from django.utils.timezone import localtime, make_aware

logger = logging.getLogger("apps.payments.tasks_receipts")


@shared_task(
    bind=True,
    max_retries=3,
    default_retry_delay=60,
    acks_late=True,
    reject_on_worker_lost=True,
    queue="receipts",  # H9: isolated from webhook tasks — slow PDF/email work
)
def generate_and_send_receipt(self, receipt_pk: str) -> dict:
    """
    Generate and email a single OfficialDonationReceipt PDF.

    Idempotent: if the PDF already exists, skips generation and sends only.
    Retries with exponential back-off on both PDF and email failures.

    Args:
        receipt_pk: str representation of the receipt UUID.

    Returns:
        dict with 'status' key ('generated_and_sent', 'resent', or 'skipped').
    """
    from apps.payments.models import OfficialDonationReceipt
    from apps.payments.services.receipt_email import send_receipt_email
    from apps.payments.services.receipt_pdf import generate_receipt_pdf, save_receipt_pdf

    try:
        receipt = (
            OfficialDonationReceipt.objects
            .select_related("donation", "donation__donor")
            .get(pk=receipt_pk)
        )
    except OfficialDonationReceipt.DoesNotExist:
        logger.error(
            "payments.task.receipt_not_found receipt_pk=%s", receipt_pk
        )
        return {"status": "not_found"}

    # Only issue receipts with status = issued
    if receipt.status != OfficialDonationReceipt.RECEIPT_STATUS_ISSUED:
        logger.info(
            "payments.task.receipt_skipped_status serial=%s status=%s",
            receipt.serial_number,
            receipt.status,
        )
        return {"status": "skipped", "reason": "not_issued"}

    # -- Phase 1: PDF generation (idempotent, serialised under DB lock) --
    #
    # C2 fix: email_sent=True is deliberately NOT set inside this atomic block.
    # Setting it here and then sending the email outside the transaction creates
    # a window where a SIGKILL/OOM between commit and send permanently marks the
    # receipt as delivered without it ever being sent — a CRA compliance failure.
    # Instead, email_sent=True is set only after a confirmed successful send (Phase 2).
    pdf_bytes = None
    was_generated = False
    try:
        with transaction.atomic():
            receipt_locked = (
                OfficialDonationReceipt.objects
                .select_related("donation", "donation__donor")
                .select_for_update()
                .get(pk=receipt.pk)
            )

            # Guard: if a concurrent worker already delivered the email, bail out.
            # Without email_sent=True inside the lock, two concurrent workers could
            # both pass this check and both call send_receipt_email — this is
            # acceptable (one duplicate CRA receipt) vs. the alternative of a receipt
            # never delivered. The atomic conditional update in Phase 2 ensures only
            # one worker "wins" the flag even if both send.
            if receipt_locked.email_sent:
                return {"status": "skipped", "reason": "email_already_sent"}

            if receipt_locked.pdf_path:
                # Already generated by another worker — load bytes outside lock below
                pass
            else:
                pdf_bytes = generate_receipt_pdf(receipt_locked)
                save_receipt_pdf(receipt_locked, pdf_bytes)
                was_generated = True
                # pdf_path is persisted by save_receipt_pdf() via _base_manager.update()
                # and set on the in-memory object. No additional save() call is needed here.

    except Exception as exc:
        logger.error(
            "payments.task.receipt_pdf_error serial=%s error_type=%s",
            receipt.serial_number,
            type(exc).__name__,
        )
        raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    # Re-fetch after the lock is released to get the current pdf_path
    receipt_locked.refresh_from_db()

    if pdf_bytes is None:
        # PDF was already on disk (generated by another worker or a previous run)
        from django.core.files.storage import default_storage
        try:
            with default_storage.open(receipt_locked.pdf_path, "rb") as fh:
                pdf_bytes = fh.read()
        except Exception as exc:
            logger.error(
                "payments.task.receipt_pdf_read_error serial=%s error_type=%s",
                receipt.serial_number,
                type(exc).__name__,
            )
            raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    # -- Phase 2: Email delivery, then mark delivered --
    #
    # C2 fix: email_sent=True is set ONLY after a confirmed successful send.
    # On failure, we log and re-raise so Celery retries. The receipt remains
    # with email_sent=False, allowing the retry to re-attempt delivery.
    # The conditional filter(email_sent=False) ensures idempotency: if two
    # concurrent workers both reach this point, only one write will take effect.
    try:
        sent = send_receipt_email(receipt_locked, pdf_bytes)
        if not sent:
            raise RuntimeError("send_receipt_email returned False")
    except Exception as exc:
        logger.error(
            "payments.receipt.email_delivery_failed receipt_pk=%s exc_type=%s",
            receipt_pk,
            type(exc).__name__,
        )
        raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    # Atomic conditional update — only sets flag if not already set by a concurrent worker.
    OfficialDonationReceipt._base_manager.filter(
        pk=receipt_pk,
        email_sent=False,
    ).update(email_sent=True, updated_at=timezone.now())

    status = "generated_and_sent" if was_generated else "resent"
    logger.info("payments.task.receipt_sent serial=%s", receipt.serial_number)
    return {"status": status}


@shared_task(
    bind=True,
    max_retries=1,
    acks_late=True,
    reject_on_worker_lost=True,  # requeue if worker is killed mid-run (CRA compliance)
    queue="receipts",  # H9: isolated queue — annual run must not starve webhook processing
)
def generate_annual_receipts(self, tax_year: int) -> dict:
    """
    Issue official donation receipts for all completed donations in tax_year
    that do not yet have an issued receipt.

    Strategy:
    - Group completed donations by donor.
    - Skip donors who already have an issued receipt for the year.
    - Single donation → one individual receipt.
    - Multiple donations → one consolidated receipt referencing the first donation
      (the model supports is_annual_consolidated).

    Each new receipt is saved and queued to generate_and_send_receipt.

    Returns:
        dict with 'processed', 'skipped', 'failed' counts.

    Logs: tax_year + counts only — NEVER donor emails.
    """
    from apps.payments.models import (
        CharitySettings,
        Donation,
        OfficialDonationReceipt,
    )

    processed = 0
    skipped = 0
    failed = 0

    # Need active charity settings to issue receipts
    try:
        charity = CharitySettings.objects.get(is_active=True)
    except CharitySettings.DoesNotExist:
        logger.error(
            "payments.task.annual_receipts.no_charity tax_year=%s", tax_year
        )
        return {"processed": 0, "skipped": 0, "failed": 0}

    # H-D fix: use timezone-aware year boundaries that cover all Canadian timezones.
    #
    # Canada spans UTC-3:30 (NL, America/St_Johns) to UTC-8 in winter (BC,
    # America/Vancouver).  Using America/Toronto (UTC-5) for both boundaries
    # excluded BC/AB donors who donate late on Dec 31 local time — a CRA
    # compliance failure (donor receives no receipt for a deductible donation).
    #
    # Start boundary: use Newfoundland time (UTC-3:30) — the easternmost zone,
    # where Jan 1 starts earliest.  This ensures we never accidentally capture a
    # late Dec 31 donation from NL in the *following* year's run.
    #   2025-01-01 00:00:00 NST = 2025-01-01 03:30:00 UTC
    #
    # End boundary: use Pacific time (UTC-8 in winter) — the westernmost zone,
    # where Dec 31 ends latest.  A BC donor giving at 22:30 PST = 06:30 UTC Jan 1
    # would be missed if we used Eastern time (UTC-5) for the end.
    #   2024-12-31 23:59:59 PST = 2025-01-01 07:59:59 UTC
    _CANADA_NL_TZ = pytz.timezone("America/St_Johns")
    _CANADA_WESTERN_TZ = pytz.timezone("America/Vancouver")

    _year_start_utc = _CANADA_NL_TZ.localize(
        datetime(tax_year, 1, 1, 0, 0, 0)
    ).astimezone(pytz.UTC)
    _year_end_utc = _CANADA_WESTERN_TZ.localize(
        datetime(tax_year, 12, 31, 23, 59, 59, 999999)
    ).astimezone(pytz.UTC)

    # All completed donations in the tax year
    completed_donations = (
        Donation.objects
        .filter(
            status="completed",
            created_at__gte=_year_start_utc,
            created_at__lte=_year_end_utc,
        )
        .select_related("donor", "payment_intent")
        .order_by("donor_id", "created_at")
    )

    total = completed_donations.count()
    logger.info(
        "payments.generate_annual_receipts.starting tax_year=%s total_donations=%s",
        tax_year,
        total,
    )

    # M-G fix: process donations donor-by-donor using itertools.groupby to avoid
    # buffering all rows in a dict simultaneously.
    #
    # The old pattern (donations_by_donor = defaultdict(list)) collected every
    # donation row into a single in-memory dict before processing anyone, negating
    # the entire benefit of .iterator(chunk_size=500). For a municipality with
    # 200k annual donors / 1.5M donations this causes an OOM kill.
    #
    # itertools.groupby consumes one contiguous group at a time: only the current
    # donor's rows are held in memory while we build and save their receipt.
    # The queryset is already sorted by (donor_id, created_at) — groupby requires
    # a sorted input to work correctly, and the sort happens in PostgreSQL.
    #
    # H4 fix: transaction.atomic() is required for PostgreSQL server-side cursors.
    # Without an open transaction, Django silently falls back to loading the entire
    # queryset into memory in one shot — defeating the purpose of .iterator() for
    # large datasets. Inner transaction.atomic() blocks inside the per-donor loop
    # nest as savepoints, which is safe in Django with PostgreSQL.
    with transaction.atomic():
        for donor_id, donor_group in itertools.groupby(
            completed_donations.iterator(chunk_size=500),
            key=attrgetter("donor_id"),
        ):
            donor_donations = list(donor_group)  # only current donor's rows in memory
            try:
                # Filter to donations with eligible_amount > 0 (outside lock — read-only)
                eligible_donations = [
                    d for d in donor_donations
                    if d.eligible_amount > Decimal("0.00")
                ]
                if not eligible_donations:
                    skipped += 1
                    continue

                # Use the first donation as the anchor (FK required by model)
                anchor = eligible_donations[0]
                is_consolidated = len(eligible_donations) > 1

                # Sum eligible amounts across all donations in year
                total_eligible = sum(d.eligible_amount for d in eligible_donations)
                total_advantage = sum(d.advantage_amount for d in eligible_donations)

                # Build charity address snapshot
                charity_address = (
                    f"{charity.charity_address_line1}, "
                    f"{charity.charity_city}, "
                    f"{charity.charity_province} "
                    f"{charity.charity_postal_code}"
                )

                # Parse donor address from snapshot (stored as free text)
                # The snapshot contains the full address string; we store it in charity_address
                # style. For individual fields, fall back to splitting or using the snapshot.
                donor_address_snapshot = anchor.donor_address_snapshot

                # OfficialDonationReceipt requires individual donor address fields.
                # Parse from the snapshot. Format stored by donation form:
                # "line1\ncity, province  postal_code"
                donor_address_parts = _parse_donor_address(donor_address_snapshot)

                # Consolidate advantage descriptions across all eligible donations
                unique_advantage_descriptions = "; ".join(
                    desc for desc in dict.fromkeys(  # preserve order, deduplicate
                        d.advantage_description for d in eligible_donations
                        if getattr(d, "advantage_description", None)
                    )
                )
                advantage_description = unique_advantage_descriptions[:255] if unique_advantage_descriptions else ""

                # Check if an issued receipt already exists for this donor/year (fast pre-check).
                # A UniqueConstraint on (donation, status=issued) prevents true duplicates at
                # the DB level — we catch IntegrityError below for the TOCTOU window.
                # Use the same UTC-converted local-time bounds (_year_start_utc / _year_end_utc)
                # as the main donation query above — not __year= which uses UTC year.
                if OfficialDonationReceipt.objects.filter(
                    donation__donor_id=donor_id,
                    donation__created_at__gte=_year_start_utc,
                    donation__created_at__lte=_year_end_utc,
                    status=OfficialDonationReceipt.RECEIPT_STATUS_ISSUED,
                ).exists():
                    skipped += 1
                    continue

                try:
                    with transaction.atomic():
                        receipt = OfficialDonationReceipt(
                            donation=anchor,
                            status=OfficialDonationReceipt.RECEIPT_STATUS_ISSUED,
                            donor_legal_name=anchor.donor_name_snapshot,
                            donor_address_line1=donor_address_parts.get("line1", donor_address_snapshot[:255]),
                            donor_city=donor_address_parts.get("city", ""),
                            donor_province=donor_address_parts.get("province", ""),
                            donor_postal_code=donor_address_parts.get("postal_code", ""),
                            # CRA date fields — use local time so a donation at 23:30 ET on Dec 31
                            # does not appear as Jan 1 on the CRA receipt due to UTC offset.
                            donation_date=localtime(anchor.created_at).date(),
                            receipt_date=localtime(timezone.now()).date(),
                            eligible_amount=total_eligible,
                            advantage_amount=total_advantage,
                            advantage_description=advantage_description,
                            charity_legal_name=charity.charity_legal_name,
                            charity_registration_number=charity.charity_registration_number,
                            charity_address=charity_address,
                            place_of_issue=charity.place_of_issue,
                            authorized_signatory_name=charity.authorized_signatory_name,
                            authorized_signatory_title=charity.authorized_signatory_title,
                            is_annual_consolidated=is_consolidated,
                        )
                        receipt.save()
                        # Queue PDF generation + email AFTER commit to avoid orphaned tasks
                        transaction.on_commit(lambda r=receipt: generate_and_send_receipt.delay(str(r.pk)))
                except IntegrityError as exc:
                    # C3 fix: only swallow the specific unique-receipt constraint violation
                    # (expected race condition when two annual receipt workers run concurrently
                    # for the same donor). Re-raise all other IntegrityErrors so real DB
                    # errors (FK violations, NOT NULL failures, etc.) surface to operators
                    # rather than being silently counted as "skipped".
                    _UNIQUE_CONSTRAINT = "payments_receipt_unique_issued_per_donation"
                    if _UNIQUE_CONSTRAINT not in str(exc):
                        raise
                    logger.info(
                        "payments.annual_receipts.duplicate_skipped donation_pk=%s",
                        anchor.pk,
                    )
                    skipped += 1
                    continue

                processed += 1

            except Exception as exc:
                logger.error(
                    "payments.task.annual_receipts.donor_error "
                    "tax_year=%s error_type=%s",
                    tax_year,
                    type(exc).__name__,
                )
                failed += 1

    logger.info(
        "payments.task.annual_receipts.done "
        "tax_year=%s processed=%s skipped=%s failed=%s",
        tax_year,
        processed,
        skipped,
        failed,
    )
    return {"processed": processed, "skipped": skipped, "failed": failed}


def _parse_donor_address(address_snapshot: str) -> dict:
    """
    Parse a donor address snapshot string into component fields.

    The Donation model stores donor_address_snapshot as a free-text field.
    We attempt to parse common Canadian address formats. Falls back gracefully.

    Expected format (set by donation form):
        "123 Main St\nOttawa, ON  K1A 0A6"
    or a single line: "123 Main St, Ottawa, ON K1A 0A6"
    """
    import re

    result = {"line1": "", "city": "", "province": "", "postal_code": ""}
    if not address_snapshot:
        return result

    lines = [ln.strip() for ln in address_snapshot.strip().splitlines() if ln.strip()]

    if len(lines) >= 2:
        result["line1"] = lines[0][:255]
        # Second line: "City, Province  PostalCode"
        second = lines[1]
        # Match "City, ON  K1A 0A6" or "City ON K1A0A6"
        m = re.match(
            r"^(.+?),?\s+([A-Z]{2})\s+([A-Z]\d[A-Z]\s*\d[A-Z]\d)$",
            second,
            re.IGNORECASE,
        )
        if m:
            result["city"] = m.group(1).strip()[:100]
            result["province"] = m.group(2).upper()[:2]
            result["postal_code"] = m.group(3).replace(" ", "").upper()
            # Re-format postal code as "A1A 1A1"
            pc = result["postal_code"]
            if len(pc) == 6:
                result["postal_code"] = f"{pc[:3]} {pc[3:]}"
        else:
            # Fallback: store second line in city
            result["city"] = second[:100]
    elif len(lines) == 1:
        result["line1"] = lines[0][:255]

    return result


@shared_task(
    bind=True,
    name="apps.payments.tasks_receipts.kickoff_annual_receipts",
    max_retries=3,
    default_retry_delay=300,  # 5 min between retries
    acks_late=True,           # M-H fix: ack only after successful completion
    reject_on_worker_lost=True,  # M-H fix: requeue if worker is SIGKILL'd mid-dispatch
    queue="receipts",
)
def kickoff_annual_receipts(self) -> dict:
    """
    Celery Beat entry-point for the annual receipt run.

    Resolves tax_year = (current year - 1) at runtime and delegates to
    generate_annual_receipts via fire-and-forget (no .get()). Blocking on
    .get() would deadlock if all workers are busy — the child task can never
    start while the parent holds a worker slot waiting for it.

    Monitor generate_annual_receipts directly in Flower or Celery events.

    Called by the 'payments.generate_annual_receipts' PeriodicTask registered
    via `python manage.py setup_periodic_tasks`.

    M-B: Idempotency guard — cache.add() is atomic; only the first concurrent
    caller gets True. Prevents double-dispatch from Beat restart, clock drift,
    or manual re-trigger, which would cause duplicate CRA receipts.
    """
    from django.core.cache import cache
    from django.utils.timezone import now

    tax_year = now().year - 1
    lock_key = f"payments:kickoff_annual_receipts:{tax_year}"

    if not cache.add(lock_key, "1", timeout=7200):  # 2h lock
        logger.warning(
            "payments.task.kickoff_annual_receipts.already_running tax_year=%s",
            tax_year,
        )
        return {"tax_year": tax_year, "status": "already_running"}

    try:
        result = generate_annual_receipts.delay(tax_year)
        logger.info(
            "payments.task.kickoff_annual_receipts.dispatched tax_year=%s task_id=%s",
            tax_year,
            result.id,
        )
        return {"tax_year": tax_year, "task_id": result.id, "status": "dispatched"}
    except Exception:
        cache.delete(lock_key)  # release lock so a retry can proceed
        raise
