"""
Celery tasks for donation receipt generation and delivery.

Security invariants:
- Donor emails NEVER logged.
- Donor names NEVER logged.
- Only serial_number, donation_pk, tax_year, and counts are logged.
"""
from __future__ import annotations

import logging
from decimal import Decimal

from celery import shared_task
from django.db import IntegrityError, transaction
from django.utils import timezone
from django.utils.timezone import localtime

logger = logging.getLogger("apps.payments.tasks_receipts")


@shared_task(
    bind=True,
    max_retries=3,
    default_retry_delay=60,
    acks_late=True,
    reject_on_worker_lost=True,
)
def generate_and_send_receipt(self, receipt_pk: str) -> dict:
    """
    Generate and email a single OfficialDonationReceipt PDF.

    Idempotent: if the PDF already exists, skips generation and sends only.
    Retries with exponential back-off on both PDF and email failures.

    Args:
        receipt_pk: str representation of the receipt UUID.

    Returns:
        dict with 'status' key ('generated_and_sent', 'resent', or 'skipped').
    """
    from apps.payments.models import OfficialDonationReceipt
    from apps.payments.services.receipt_email import send_receipt_email
    from apps.payments.services.receipt_pdf import generate_receipt_pdf, save_receipt_pdf

    try:
        receipt = (
            OfficialDonationReceipt.objects
            .select_related("donation", "donation__donor")
            .get(pk=receipt_pk)
        )
    except OfficialDonationReceipt.DoesNotExist:
        logger.error(
            "payments.task.receipt_not_found receipt_pk=%s", receipt_pk
        )
        return {"status": "not_found"}

    # Only issue receipts with status = issued
    if receipt.status != OfficialDonationReceipt.RECEIPT_STATUS_ISSUED:
        logger.info(
            "payments.task.receipt_skipped_status serial=%s status=%s",
            receipt.serial_number,
            receipt.status,
        )
        return {"status": "skipped", "reason": "not_issued"}

    # -- PDF generation (idempotent, serialised under DB lock) --
    pdf_bytes = None
    was_generated = False
    try:
        with transaction.atomic():
            receipt_locked = (
                OfficialDonationReceipt.objects
                .select_related("donation", "donation__donor")
                .select_for_update()
                .get(pk=receipt.pk)
            )

            # Guard: if a concurrent worker already sent the email, bail out.
            # This prevents duplicate CRA receipts when two workers both pass
            # the initial status check and then race into this atomic block.
            # select_for_update() ensures only one worker holds the lock at a
            # time; the second worker sees email_sent=True and returns early.
            if receipt_locked.email_sent:
                return {"status": "skipped", "reason": "email_already_sent"}

            if receipt_locked.pdf_path:
                # Already generated by another worker — load bytes outside lock below
                pass
            else:
                pdf_bytes = generate_receipt_pdf(receipt_locked)
                save_receipt_pdf(receipt_locked, pdf_bytes)
                was_generated = True

            # Persist email_sent=True inside the same atomic block so the flag
            # is committed atomically under the row lock.  If the email send
            # below fails we reset the flag so the next Celery retry can
            # re-attempt delivery (see reset logic after the except block).
            receipt_locked.email_sent = True
            receipt_locked.save(update_fields=["email_sent", "updated_at"])

    except Exception as exc:
        logger.error(
            "payments.task.receipt_pdf_error serial=%s error_type=%s",
            receipt.serial_number,
            type(exc).__name__,
        )
        raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    # Re-fetch after the lock is released to get the current pdf_path
    receipt_locked.refresh_from_db()

    if pdf_bytes is None:
        # PDF was already on disk (generated by another worker or a previous run)
        from django.core.files.storage import default_storage
        try:
            with default_storage.open(receipt_locked.pdf_path, "rb") as fh:
                pdf_bytes = fh.read()
        except Exception as exc:
            logger.error(
                "payments.task.receipt_pdf_read_error serial=%s error_type=%s",
                receipt.serial_number,
                type(exc).__name__,
            )
            raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    # -- Email delivery --
    # email_sent=True is already committed.  On failure we reset the flag via
    # _base_manager (bypasses the OfficialDonationReceipt QuerySet guard that
    # blocks bulk updates) so the next Celery retry can re-attempt delivery.
    try:
        sent = send_receipt_email(receipt_locked, pdf_bytes)
        if not sent:
            raise RuntimeError("send_receipt_email returned False")
    except Exception as exc:
        logger.error(
            "payments.task.receipt_email_error serial=%s error_type=%s",
            receipt.serial_number,
            type(exc).__name__,
        )
        # Reset flag so next retry attempt is not blocked by the guard above.
        OfficialDonationReceipt._base_manager.filter(pk=receipt_locked.pk).update(
            email_sent=False,
            updated_at=timezone.now(),
        )
        raise self.retry(exc=exc, countdown=60 * (2 ** self.request.retries))

    status = "generated_and_sent" if was_generated else "resent"
    logger.info("payments.task.receipt_sent serial=%s", receipt.serial_number)
    return {"status": status}


@shared_task(
    bind=True,
    max_retries=1,
    acks_late=True,
)
def generate_annual_receipts(self, tax_year: int) -> dict:
    """
    Issue official donation receipts for all completed donations in tax_year
    that do not yet have an issued receipt.

    Strategy:
    - Group completed donations by donor.
    - Skip donors who already have an issued receipt for the year.
    - Single donation → one individual receipt.
    - Multiple donations → one consolidated receipt referencing the first donation
      (the model supports is_annual_consolidated).

    Each new receipt is saved and queued to generate_and_send_receipt.

    Returns:
        dict with 'processed', 'skipped', 'failed' counts.

    Logs: tax_year + counts only — NEVER donor emails.
    """
    from apps.payments.models import (
        CharitySettings,
        Donation,
        OfficialDonationReceipt,
    )

    processed = 0
    skipped = 0
    failed = 0

    # Need active charity settings to issue receipts
    try:
        charity = CharitySettings.objects.get(is_active=True)
    except CharitySettings.DoesNotExist:
        logger.error(
            "payments.task.annual_receipts.no_charity tax_year=%s", tax_year
        )
        return {"processed": 0, "skipped": 0, "failed": 0}

    # All completed donations in the tax year
    completed_donations = (
        Donation.objects
        .filter(
            status="completed",
            created_at__year=tax_year,
        )
        .select_related("donor", "payment_intent")
        .order_by("donor_id", "created_at")
    )

    total = completed_donations.count()
    logger.info(
        "payments.generate_annual_receipts.starting tax_year=%s total_donations=%s",
        tax_year,
        total,
    )

    # Group by donor_id
    from collections import defaultdict
    donations_by_donor: dict = defaultdict(list)
    # chunk_size=500: server-side cursor fetches 500 rows at a time.
    # Prevents loading hundreds of thousands of donation rows into memory at once.
    # Celery workers have limited RAM and the annual run processes all donors.
    for donation in completed_donations.iterator(chunk_size=500):
        donations_by_donor[donation.donor_id].append(donation)

    for donor_id, donor_donations in donations_by_donor.items():
        try:
            # Filter to donations with eligible_amount > 0 (outside lock — read-only)
            eligible_donations = [
                d for d in donor_donations
                if d.eligible_amount > Decimal("0.00")
            ]
            if not eligible_donations:
                skipped += 1
                continue

            # Use the first donation as the anchor (FK required by model)
            anchor = eligible_donations[0]
            is_consolidated = len(eligible_donations) > 1

            # Sum eligible amounts across all donations in year
            total_eligible = sum(d.eligible_amount for d in eligible_donations)
            total_advantage = sum(d.advantage_amount for d in eligible_donations)

            # Build charity address snapshot
            charity_address = (
                f"{charity.charity_address_line1}, "
                f"{charity.charity_city}, "
                f"{charity.charity_province} "
                f"{charity.charity_postal_code}"
            )

            # Parse donor address from snapshot (stored as free text)
            # The snapshot contains the full address string; we store it in charity_address
            # style. For individual fields, fall back to splitting or using the snapshot.
            donor_address_snapshot = anchor.donor_address_snapshot

            # OfficialDonationReceipt requires individual donor address fields.
            # Parse from the snapshot. Format stored by donation form:
            # "line1\ncity, province  postal_code"
            donor_address_parts = _parse_donor_address(donor_address_snapshot)

            # Consolidate advantage descriptions across all eligible donations
            unique_advantage_descriptions = "; ".join(
                desc for desc in dict.fromkeys(  # preserve order, deduplicate
                    d.advantage_description for d in eligible_donations
                    if getattr(d, "advantage_description", None)
                )
            )
            advantage_description = unique_advantage_descriptions[:255] if unique_advantage_descriptions else ""

            # Check if an issued receipt already exists for this donor/year (fast pre-check).
            # A UniqueConstraint on (donation, status=issued) prevents true duplicates at
            # the DB level — we catch IntegrityError below for the TOCTOU window.
            if OfficialDonationReceipt.objects.filter(
                donation__donor_id=donor_id,
                donation__created_at__year=tax_year,  # Django ORM __year respects USE_TZ + TIME_ZONE
                status=OfficialDonationReceipt.RECEIPT_STATUS_ISSUED,
            ).exists():
                skipped += 1
                continue

            try:
                with transaction.atomic():
                    receipt = OfficialDonationReceipt(
                        donation=anchor,
                        status=OfficialDonationReceipt.RECEIPT_STATUS_ISSUED,
                        donor_legal_name=anchor.donor_name_snapshot,
                        donor_address_line1=donor_address_parts.get("line1", donor_address_snapshot[:255]),
                        donor_city=donor_address_parts.get("city", ""),
                        donor_province=donor_address_parts.get("province", ""),
                        donor_postal_code=donor_address_parts.get("postal_code", ""),
                        # CRA date fields — use local time so a donation at 23:30 ET on Dec 31
                        # does not appear as Jan 1 on the CRA receipt due to UTC offset.
                        donation_date=localtime(anchor.created_at).date(),
                        receipt_date=localtime(timezone.now()).date(),
                        eligible_amount=total_eligible,
                        advantage_amount=total_advantage,
                        advantage_description=advantage_description,
                        charity_legal_name=charity.charity_legal_name,
                        charity_registration_number=charity.charity_registration_number,
                        charity_address=charity_address,
                        place_of_issue=charity.place_of_issue,
                        authorized_signatory_name=charity.authorized_signatory_name,
                        authorized_signatory_title=charity.authorized_signatory_title,
                        is_annual_consolidated=is_consolidated,
                    )
                    receipt.save()
                    # Queue PDF generation + email AFTER commit to avoid orphaned tasks
                    transaction.on_commit(lambda r=receipt: generate_and_send_receipt.delay(str(r.pk)))
            except IntegrityError:
                # Concurrent worker already created a receipt for this donor/year.
                # The DB UniqueConstraint on (donation_id) for issued receipts is the true guard.
                logger.info(
                    "payments.generate_annual_receipts.duplicate_skipped donor_id=%s tax_year=%s",
                    str(donor_id),
                    tax_year,
                )
                skipped += 1
                continue

            processed += 1

        except Exception as exc:
            logger.error(
                "payments.task.annual_receipts.donor_error "
                "tax_year=%s error_type=%s",
                tax_year,
                type(exc).__name__,
            )
            failed += 1

    logger.info(
        "payments.task.annual_receipts.done "
        "tax_year=%s processed=%s skipped=%s failed=%s",
        tax_year,
        processed,
        skipped,
        failed,
    )
    return {"processed": processed, "skipped": skipped, "failed": failed}


def _parse_donor_address(address_snapshot: str) -> dict:
    """
    Parse a donor address snapshot string into component fields.

    The Donation model stores donor_address_snapshot as a free-text field.
    We attempt to parse common Canadian address formats. Falls back gracefully.

    Expected format (set by donation form):
        "123 Main St\nOttawa, ON  K1A 0A6"
    or a single line: "123 Main St, Ottawa, ON K1A 0A6"
    """
    import re

    result = {"line1": "", "city": "", "province": "", "postal_code": ""}
    if not address_snapshot:
        return result

    lines = [ln.strip() for ln in address_snapshot.strip().splitlines() if ln.strip()]

    if len(lines) >= 2:
        result["line1"] = lines[0][:255]
        # Second line: "City, Province  PostalCode"
        second = lines[1]
        # Match "City, ON  K1A 0A6" or "City ON K1A0A6"
        m = re.match(
            r"^(.+?),?\s+([A-Z]{2})\s+([A-Z]\d[A-Z]\s*\d[A-Z]\d)$",
            second,
            re.IGNORECASE,
        )
        if m:
            result["city"] = m.group(1).strip()[:100]
            result["province"] = m.group(2).upper()[:2]
            result["postal_code"] = m.group(3).replace(" ", "").upper()
            # Re-format postal code as "A1A 1A1"
            pc = result["postal_code"]
            if len(pc) == 6:
                result["postal_code"] = f"{pc[:3]} {pc[3:]}"
        else:
            # Fallback: store second line in city
            result["city"] = second[:100]
    elif len(lines) == 1:
        result["line1"] = lines[0][:255]

    return result


@shared_task(
    bind=True,
    name="apps.payments.tasks_receipts.kickoff_annual_receipts",
    max_retries=0,
    acks_late=False,
)
def kickoff_annual_receipts(self) -> dict:
    """
    Celery Beat entry-point for the annual receipt run.

    Resolves tax_year = (current year - 1) at runtime and delegates to
    generate_annual_receipts via fire-and-forget (no .get()). Blocking on
    .get() would deadlock if all workers are busy — the child task can never
    start while the parent holds a worker slot waiting for it.

    Monitor generate_annual_receipts directly in Flower or Celery events.

    Called by the 'payments.generate_annual_receipts' PeriodicTask registered
    via `python manage.py setup_periodic_tasks`.
    """
    from django.utils.timezone import now

    tax_year = now().year - 1
    result = generate_annual_receipts.delay(tax_year)
    logger.info(
        "payments.task.kickoff_annual_receipts.dispatched tax_year=%s task_id=%s",
        tax_year,
        result.id,
    )
    return {"tax_year": tax_year, "task_id": result.id, "status": "dispatched"}
