# Generated by Django 5.2.3 on 2026-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentcategory',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If True, consent cannot be withdrawn — required for essential service delivery.'),
        ),
        migrations.AlterField(
            model_name='dataexportrequest',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Internal file path — do not expose to citizens.', max_length=500),
        ),
    ]
