# Generated by Django 5.2.3 on 2026-07-07 03:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("consent", "0007_govstack_alignment"),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="ConsentSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        help_text="JSON serialization of the fields that were signed, per GovStack spec."
                    ),
                ),
                ("signature", models.TextField(help_text="Signature of payload hash.")),
                (
                    "verification_method",
                    models.CharField(
                        help_text="Well-known string denoting the signing method (e.g. 'RS256', 'none').",
                        max_length=100,
                    ),
                ),
                (
                    "verification_payload",
                    models.TextField(
                        help_text="Internally generated serialized version of the signed data."
                    ),
                ),
                (
                    "verification_payload_hash",
                    models.CharField(
                        help_text="Cryptographic hash of verificationPayload.", max_length=255
                    ),
                ),
                (
                    "verification_signed_by",
                    models.CharField(
                        help_text="Identifier for the signing party at the time of signing (e.g. fingerprint, email, user ID).",
                        max_length=500,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="ISO 8601 timestamp of when the signature was created."
                    ),
                ),
                (
                    "verification_artifact",
                    models.TextField(
                        blank=True,
                        help_text="Scanned object, image, or other verification artefact.",
                    ),
                ),
                (
                    "verification_signed_as",
                    models.CharField(
                        blank=True,
                        help_text="Relationship of the signer to the individual: 'individual' or 'delegate'.",
                        max_length=50,
                    ),
                ),
                (
                    "verification_jws_header",
                    models.TextField(
                        blank=True,
                        help_text="JWS serialized object (RFC7515) — alternative to verificationMethod.",
                    ),
                ),
                (
                    "signed_without_object_reference",
                    models.BooleanField(
                        default=False,
                        help_text="True if objectReference was omitted from the signed payload.",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Name of the schema model that objectReference points to ('signature' or 'revision').",
                        max_length=50,
                    ),
                ),
                (
                    "object_reference",
                    models.CharField(
                        blank=True,
                        help_text="Back-reference to the objectType that was signed.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Signature",
                "verbose_name_plural": "Consent Signatures",
            },
        ),
        migrations.RenameIndex(
            model_name="consentrevision",
            new_name="consent_con_schema__4ac997_idx",
            old_name="consent_rev_schema__f5b8a2_idx",
        ),
        migrations.AlterField(
            model_name="consentauditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("granted", "Granted"),
                    ("withdrawn", "Withdrawn"),
                    ("export_requested", "Export Requested"),
                    ("export_ready", "Export Ready"),
                    ("export_delivered", "Export Delivered"),
                    ("export_expired", "Export Expired"),
                    ("export_failed", "Export Failed"),
                    ("export_downloaded", "Export Downloaded by Citizen"),
                    ("export_marked_delivered", "Marked Delivered by Staff"),
                    ("rtbf_requested", "Right to Be Forgotten Requested"),
                    ("rtbf_completed", "Right to Be Forgotten Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="consentpolicy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="consentpolicy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="consentpolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="data_agreement_revision_hash",
            field=models.CharField(
                blank=True,
                help_text="Copy of the Revision's hash at the time of consent. Ensures against tampering with the original Data Agreement.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="consentrevision",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="consentwebhook",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="consentwebhook",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="consentwebhook",
            name="subscribed_events",
            field=models.JSONField(
                default=list,
                help_text="List of event type strings this webhook is subscribed to. Known events: ['consent.granted', 'consent.withdrawn', 'consent.export.requested', 'consent.export.ready']",
            ),
        ),
        migrations.AlterField(
            model_name="consentwebhook",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="consentsignature",
            name="consent_record",
            field=models.OneToOneField(
                help_text="The ConsentRecord this signature covers.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signature_obj",
                to="consent.consentrecord",
            ),
        ),
    ]
