# Generated by Django 5.2.3 on 2026-07-25 09:40
#
# Fix 4 (GovStack Consent BB certifiability review, 2026-07-25): DB-level
# partial unique constraint guaranteeing at most one is_current=True
# ConsentRecord row per (citizen, category). See ConsentRecord.Meta.constraints
# in models.py and the IntegrityError handling in ConsentService.grant()
# (services.py) for the full rationale.
#
# NOTE: `manage.py makemigrations consent` also detected three unrelated,
# pre-existing AlterField changes (ConsentRecord.state, ConsentSignature.
# verification_type, ConsentWebhook.secret_key help_text/type) that predate
# this fix and are out of scope for it — they were deliberately left out of
# this migration per the "apply exactly the 5 items, don't go looking for
# other things to fix" instruction. `makemigrations --check --dry-run` will
# still report those three as pending; that is pre-existing drift, not
# something introduced by this change.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("consent", "0016_consentwebhook_payload_replay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("citizen", "category"),
                name="unique_current_consent_record_per_citizen_category",
            ),
        ),
    ]
