# Generated by Django 5.2.3 on 2026-07-26 22:19

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0017_consent_record_is_current_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentpolicy',
            name='harness_alias_id',
            field=models.PositiveIntegerField(blank=True, help_text="GovStack reference-harness compatibility alias ONLY — not part of the real Policy identity, and not a GovStack spec field. The real primary key for a Policy is (and remains) a UUID, per GovStack v23Q4's own Policy.id schema (an opaque string ID — UUID is a perfectly spec-conformant choice). The upstream GovStackWorkingGroup/bb-consent reference test harness (test/gherkin/features/smoke.feature) hardcodes GET /service/policy/1/ with no environment-variable override for that literal '1', so a plain UUID-only lookup can never satisfy it. This field lets exactly one seeded 'well-known' Policy be reachable via that harness literal (see seed_consent_policy management command) without changing the real PK scheme for every other Policy. NULL for every ordinary Policy; only ever set to 1 for the harness-compatibility row. See ServicePolicyDetailView._resolve_policy_pk_or_alias() for the lookup logic.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='state',
            field=models.CharField(choices=[('unsigned', 'Unsigned'), ('pending', 'Pending'), ('signed', 'Signed'), ('revoked', 'Revoked')], db_index=True, default='unsigned', help_text='GovStack signing state: unsigned / pending / signed / revoked.', max_length=30),
        ),
        migrations.AlterField(
            model_name='consentsignature',
            name='verification_type',
            field=models.CharField(choices=[('string', 'String (non-cryptographic)'), ('rs256', 'RS256 (RSA + SHA-256)'), ('ed25519', 'Ed25519'), ('ps256', 'PS256 (RSA-PSS + SHA-256)'), ('pgp', 'PGP')], default='string', help_text='Signing algorithm (GovStack verificationType enum: string/rs256/ed25519/ps256).', max_length=10),
        ),
        migrations.AlterField(
            model_name='consentwebhook',
            name='secret_key',
            field=apps.core.fields.EncryptedCharField(editable=True, help_text='HMAC secret key used to sign payloads (SHA-256). Stored Fernet-encrypted at rest; returned in API responses as required by GovStack spec.', max_length=500),
        ),
    ]
