"""
Serializers for the Portal API building block.

Design decisions:
- ``submission_data`` is excluded from the list serializer to avoid leaking
  potentially sensitive form data in paginated responses. Consumers that need
  the full payload must hit the detail endpoint.
- All write serializers validate inputs explicitly rather than relying solely
  on model-level validation so that errors are returned at the API boundary
  before any DB round-trip.
- ``reference_number`` is read-only; it is generated by the model's save()
  method and must never be supplied by the client.
- ``internal_notes`` is never exposed — staff-only field.
"""

import json

from rest_framework import serializers

from apps.portal.models import ServiceRequest

# Maximum byte-size for submission_data JSON.  64 KB is generous for any
# government form while preventing trivial memory-pressure DoS attacks.
_SUBMISSION_DATA_MAX_BYTES = 65_536
_SUBMISSION_DATA_MAX_KEYS = 200


class ServiceRequestSerializer(serializers.ModelSerializer):
    """
    Read serializer for list / collection responses.

    ``submission_data`` is intentionally omitted here; use
    ``ServiceRequestDetailSerializer`` for the full payload.
    """

    status_display = serializers.CharField(
        source="get_status_display",
        read_only=True,
        help_text="Human-readable status label.",
    )

    class Meta:
        model = ServiceRequest
        fields = [
            "reference_number",
            "service_name",
            "status",
            "status_display",
            "created_at",
            "expires_at",
        ]
        read_only_fields = [
            "reference_number",
            "status",
            "status_display",
            "created_at",
            "expires_at",
        ]


class ServiceRequestDetailSerializer(ServiceRequestSerializer):
    """
    Read serializer for single-resource (retrieve) responses.

    Extends the list serializer by adding ``submission_data``. The field
    is read-only after creation — mutations go through dedicated action
    endpoints (e.g. cancel).
    """

    submission_data = serializers.JSONField(
        read_only=True,
        help_text="Form data submitted by the citizen at the time of creation.",
    )

    class Meta(ServiceRequestSerializer.Meta):
        fields = ServiceRequestSerializer.Meta.fields + ["submission_data"]
        read_only_fields = ServiceRequestSerializer.Meta.read_only_fields + [
            "submission_data",
        ]


class CreateServiceRequestSerializer(serializers.Serializer):
    """
    Write serializer for creating a new ServiceRequest.

    We use a plain Serializer (not ModelSerializer) so that we can delegate
    the actual DB write to the service layer, which handles atomic creation,
    status-update bookkeeping, and on-commit hooks.
    """

    service_name = serializers.CharField(
        required=True,
        max_length=255,
        allow_blank=False,
        help_text="Human-readable name of the service being requested.",
    )
    submission_data = serializers.DictField(
        required=True,
        help_text="Form field values as a JSON object.",
    )

    def validate_service_name(self, value: str) -> str:
        value = value.strip()
        if not value:
            raise serializers.ValidationError("service_name must not be blank.")
        return value

    def validate_submission_data(self, value) -> dict:
        if not isinstance(value, dict):
            raise serializers.ValidationError(
                "submission_data must be a JSON object (dict), not a list or scalar."
            )
        if len(value) > _SUBMISSION_DATA_MAX_KEYS:
            raise serializers.ValidationError(
                f"submission_data may not contain more than {_SUBMISSION_DATA_MAX_KEYS} "
                "top-level keys."
            )
        try:
            serialized = json.dumps(value, ensure_ascii=False).encode("utf-8")
        except (TypeError, ValueError) as exc:
            raise serializers.ValidationError(
                f"submission_data contains a non-serialisable value: {type(exc).__name__}"
            ) from exc
        if len(serialized) > _SUBMISSION_DATA_MAX_BYTES:
            raise serializers.ValidationError(
                f"submission_data exceeds the maximum allowed size of "
                f"{_SUBMISSION_DATA_MAX_BYTES // 1024} KB."
            )
        return value


class CancelServiceRequestSerializer(serializers.Serializer):
    """
    Write serializer for citizen-initiated cancellation.

    ``reason`` is optional and forwarded to the service layer as a
    citizen-visible note appended to the standard cancellation message.
    """

    reason = serializers.CharField(
        required=False,
        allow_blank=True,
        default="",
        max_length=1000,
        help_text="Optional reason for cancellation (citizen-visible).",
    )
