# Generated by Django 5.2.3 on 2026-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("audit", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="auditlogentry",
            name="outcome",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                db_index=True,
                default="success",
                max_length=16,
                verbose_name="Outcome",
            ),
        ),
    ]
