# Generated by Django 5.2.3 on 2026-06-29 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('object_id', models.CharField(max_length=64, verbose_name='Object ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('waiting', 'Waiting for information'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32, verbose_name='Status')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due at')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3, verbose_name='Priority')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Work item',
                'verbose_name_plural': 'Work items',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(max_length=64, verbose_name='Action')),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workitem', verbose_name='Work item')),
            ],
            options={
                'verbose_name': 'Work item history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to', 'status'], name='workflows_w_assigne_028b30_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_01cfe3_idx'),
        ),
    ]
