# Generated by Django 5.2.3 on 2026-06-29 02:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("contenttypes", "0002_remove_content_type_name"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="WorkItemComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("body", models.TextField(verbose_name="Comment")),
            ],
            options={
                "verbose_name": "Work item comment",
                "verbose_name_plural": "Work item comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="workitemhistory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Work item history",
                "verbose_name_plural": "Work item history entries",
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when status transitions to completed or cancelled.",
                null=True,
                verbose_name="Completed at",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description of the work required.",
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Escalated at"),
        ),
        migrations.AddField(
            model_name="workitem",
            name="escalation_level",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0=normal, 1=supervisor, 2=director.",
                verbose_name="Escalation level",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="sla_breached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by periodic task when due_at passes without completion.",
                null=True,
                verbose_name="SLA breached at",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_work_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Critical"), (2, "High"), (3, "Normal"), (4, "Low")],
                db_index=True,
                default=3,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="workitemhistory",
            name="new_status",
            field=models.CharField(blank=True, max_length=32, verbose_name="New status"),
        ),
        migrations.AlterField(
            model_name="workitemhistory",
            name="old_status",
            field=models.CharField(blank=True, max_length=32, verbose_name="Old status"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["status", "due_at"], name="workflows_w_status_a74a6e_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["escalation_level", "status"], name="workflows_w_escalat_42e554_idx"
            ),
        ),
        migrations.AddField(
            model_name="workitemcomment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_item_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="workitemcomment",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="workflows.workitem",
                verbose_name="Work item",
            ),
        ),
    ]
