# Generated by hand — Wave 1 (Analytics & Reporting BB scaffold)
# Models: ReportSnapshot, ExportRecord
# See apps/reports/models.py for field definitions and PIPEDA annotations.
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("donations", "Donations & CRA"),
                            ("operational", "Operational"),
                        ],
                        max_length=20,
                        verbose_name="Report type",
                    ),
                ),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar year, e.g. 2025.",
                        verbose_name="Period year",
                    ),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar month 1–12.",
                        verbose_name="Period month",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text=(
                            "Pre-computed aggregate metrics dict. Schema varies by "
                            "report_type — see docs/analytics-reporting-bb-spec.md §4.1."
                        ),
                        verbose_name="Aggregated data",
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of source rows aggregated into this snapshot.",
                        verbose_name="Source row count",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last computed at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report snapshot",
                "verbose_name_plural": "Report snapshots",
                "ordering": ["-period_year", "-period_month", "report_type"],
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("reconciliation", "Payment reconciliation"),
                            ("t3010_prep", "T3010 preparatory data"),
                            ("receipts", "Donation receipts list"),
                            ("revenue", "Monthly revenue"),
                            ("refunds", "Refund summary"),
                        ],
                        max_length=30,
                        verbose_name="Export type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("pdf", "PDF"),
                        ],
                        max_length=5,
                        verbose_name="Format",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(verbose_name="Period start"),
                ),
                (
                    "period_end",
                    models.DateField(verbose_name="Period end"),
                ),
                (
                    "actor_pk",
                    models.UUIDField(
                        help_text=(
                            "UUID primary key of the staff user who triggered this export."
                        ),
                        verbose_name="Actor PK",
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text=(
                            "Client IP with last octet (IPv4) or last 80 bits (IPv6) zeroed "
                            "before storage — PIPEDA data minimization."
                        ),
                        null=True,
                        verbose_name="Actor IP (masked)",
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of data rows included in the export.",
                        verbose_name="Row count",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Exported at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export record",
                "verbose_name_plural": "Export records",
                "ordering": ["-created_at"],
            },
        ),
        # ── Unique constraint: one snapshot per (report_type, year, month) ──
        migrations.AlterUniqueTogether(
            name="reportsnapshot",
            unique_together={("report_type", "period_year", "period_month")},
        ),
        # ── Indexes ──────────────────────────────────────────────────────────
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(
                fields=["report_type", "period_year", "period_month"],
                name="rpt_snap_type_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrecord",
            index=models.Index(
                fields=["export_type", "created_at"],
                name="rpt_exp_type_ts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrecord",
            index=models.Index(
                fields=["actor_pk", "created_at"],
                name="rpt_exp_actor_ts_idx",
            ),
        ),
    ]
