# Generated by Django 5.2.3 on 2026-07-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrecord',
            name='actor_pk',
            field=models.BigIntegerField(help_text='Integer primary key of the staff user who triggered this export. Stored as BigIntegerField to match User.pk (BigAutoField). Never stores email, name, or any other PII.', verbose_name='Actor PK'),
        ),
    ]
