# Generated by Django 5.2.3 on 2026-06-29 00:16

import django.db.models.deletion
import taggit.managers
import wagtail.fields
import wagtail.images.models
import wagtail.models.media
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Short summary used in search results and social media previews (max 500 chars).', max_length=500, verbose_name='Introduction')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('call_to_action', 13), ('accordion', 18), ('alert', 22)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2 — Section heading'), ('h3', 'H3 — Sub-section heading'), ('h4', 'H4 — Sub-sub-section heading')], 'help_text': "Use headings in order — don't skip levels (e.g., don't jump from H2 to H4).", 'label': 'Heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Displayed below the image. Use for attribution or context.', 'label': 'Caption', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional — makes the image a clickable link.', 'label': 'Link URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('link', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Body text', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (solid)'), ('secondary', 'Secondary (outline)')], 'label': 'Button style'}), 13: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9), ('button_text', 10), ('button_url', 11), ('button_style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Question / Title'}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Answer / Content'}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Items'}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informational'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error / Important')], 'label': 'Alert type'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Content'}), 22: ('wagtail.blocks.StructBlock', [[('alert_type', 19), ('title', 20), ('body', 21)]], {})}, verbose_name='Page body')),
            ],
            options={
                'verbose_name': 'Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name, e.g. "header" or "footer".', max_length=100, unique=True, verbose_name='Menu name')),
            ],
            options={
                'verbose_name': 'Navigation menu',
                'verbose_name_plural': 'Navigation menus',
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'News index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Services index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', wagtail.fields.RichTextField(verbose_name='Message')),
                ('alert_type', models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16, verbose_name='Alert type')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this alert without deleting it.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Site alert',
                'verbose_name_plural': 'Site alerts',
            },
        ),
        migrations.CreateModel(
            name='CustomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for people who cannot see it. Leave blank only if the image is purely decorative.', max_length=255, verbose_name='Alt text')),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(max_length=255, verbose_name='Hero heading')),
                ('hero_subheading', models.CharField(blank=True, help_text='Optional short sentence below the main heading.', max_length=500, verbose_name='Hero subheading')),
                ('hero_cta_text', models.CharField(blank=True, max_length=100, verbose_name='Hero button text')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('call_to_action', 13), ('accordion', 18), ('alert', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2 — Section heading'), ('h3', 'H3 — Sub-section heading'), ('h4', 'H4 — Sub-sub-section heading')], 'help_text': "Use headings in order — don't skip levels (e.g., don't jump from H2 to H4).", 'label': 'Heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Displayed below the image. Use for attribution or context.', 'label': 'Caption', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional — makes the image a clickable link.', 'label': 'Link URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('link', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Body text', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (solid)'), ('secondary', 'Secondary (outline)')], 'label': 'Button style'}), 13: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9), ('button_text', 10), ('button_url', 11), ('button_style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Question / Title'}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Answer / Content'}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Items'}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informational'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error / Important')], 'label': 'Alert type'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Content'}), 22: ('wagtail.blocks.StructBlock', [[('alert_type', 19), ('title', 20), ('body', 21)]], {})}, verbose_name='Page body')),
                ('hero_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero button destination')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.customimage', verbose_name='Hero image')),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(verbose_name='Publication date')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Author')),
                ('summary', models.TextField(help_text='Used in the news listing and social media previews.', max_length=300, verbose_name='Summary')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('call_to_action', 13), ('accordion', 18), ('alert', 22)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2 — Section heading'), ('h3', 'H3 — Sub-section heading'), ('h4', 'H4 — Sub-sub-section heading')], 'help_text': "Use headings in order — don't skip levels (e.g., don't jump from H2 to H4).", 'label': 'Heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Displayed below the image. Use for attribution or context.', 'label': 'Caption', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional — makes the image a clickable link.', 'label': 'Link URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('link', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Body text', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (solid)'), ('secondary', 'Secondary (outline)')], 'label': 'Button style'}), 13: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9), ('button_text', 10), ('button_url', 11), ('button_style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Question / Title'}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Answer / Content'}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Items'}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informational'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error / Important')], 'label': 'Alert type'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Content'}), 22: ('wagtail.blocks.StructBlock', [[('alert_type', 19), ('title', 20), ('body', 21)]], {})}, verbose_name='Article body')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.customimage', verbose_name='Featured image')),
            ],
            options={
                'verbose_name': 'News article',
                'ordering': ['-publication_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(help_text='One or two sentences describing this service. Shown in the services directory.', max_length=300, verbose_name='Summary')),
                ('category', models.CharField(choices=[('permits', 'Permits & licences'), ('infrastructure', 'Roads & infrastructure'), ('recreation', 'Parks & recreation'), ('taxes', 'Taxes & finance'), ('environment', 'Environment & waste'), ('planning', 'Planning & development'), ('other', 'Other')], db_index=True, default='other', max_length=32, verbose_name='Category')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('image', 7), ('call_to_action', 13), ('accordion', 18), ('alert', 22)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2 — Section heading'), ('h3', 'H3 — Sub-section heading'), ('h4', 'H4 — Sub-sub-section heading')], 'help_text': "Use headings in order — don't skip levels (e.g., don't jump from H2 to H4).", 'label': 'Heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.cms.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Displayed below the image. Use for attribution or context.', 'label': 'Caption', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional — makes the image a clickable link.', 'label': 'Link URL', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('link', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Body text', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (solid)'), ('secondary', 'Secondary (outline)')], 'label': 'Button style'}), 13: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9), ('button_text', 10), ('button_url', 11), ('button_style', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Question / Title'}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Answer / Content'}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Items'}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informational'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error / Important')], 'label': 'Alert type'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Content'}), 22: ('wagtail.blocks.StructBlock', [[('alert_type', 19), ('title', 20), ('body', 21)]], {})}, verbose_name='Service details')),
                ('online_available', models.BooleanField(default=False, help_text='Check if citizens can complete this service entirely online.', verbose_name='Available online')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Contact phone')),
                ('processing_time', models.CharField(blank=True, help_text='Plain language estimate, e.g. "5–10 business days".', max_length=100, verbose_name='Typical processing time')),
                ('fee', models.CharField(blank=True, help_text='e.g. "Free", "$50", "Varies — see fee schedule".', max_length=100, verbose_name='Fee')),
                ('online_form', models.ForeignKey(blank=True, help_text='Link to the form page for online applications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Online form page')),
            ],
            options={
                'verbose_name': 'Service page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CustomRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='cms.customimage')),
            ],
            options={
                'unique_together': {('image', 'filter_spec', 'focal_point_key')},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
    ]
