# Generated by Django 5.2.3 on 2026-06-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'News article'},
        ),
    ]
