# Generated by Django 5.2.3 on 2026-07-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("appointments", "0009_add_created_at_indexes"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelOptions(
            name="slot",
            options={
                "ordering": ["start_datetime"],
                "permissions": [("view_slot_video_urls", "Can view slot video join URLs")],
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
            },
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                help_text="ISO 8601 weekday: 1=Monday, 7=Sunday. Consistent with Python date.isoweekday().",
                verbose_name="Day of week",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="end_time",
            field=models.TimeField(
                help_text="End of availability window (exclusive) in the staff's location timezone. Must be strictly after start_time.",
                verbose_name="End time",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="start_time",
            field=models.TimeField(
                help_text="Start of availability window in the staff member's location timezone (see staff.location.timezone). The slot generation service converts this to UTC before creating Slot records.",
                verbose_name="Start time",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="valid_from",
            field=models.DateField(
                help_text="First calendar date this template is active (inclusive).",
                verbose_name="Valid from",
            ),
        ),
        migrations.AlterField(
            model_name="availabilitytemplate",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Last calendar date this template is active (inclusive). None = open-ended (no expiry). Must be on or after valid_from when set.",
                null=True,
                verbose_name="Valid until",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="appointment_type",
            field=models.ForeignKey(
                help_text="The schedulable appointment variant this slot provides.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="appointments.appointmenttype",
                verbose_name="Appointment type",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Maximum number of clients that can be booked into this slot. Matches appointment_type.capacity_per_slot at generation time. May be reduced by admin for specific slots (e.g., staff illness mid-day).",
                verbose_name="Capacity",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="effective_end",
            field=models.DateTimeField(
                help_text="end_datetime plus buffer_after_minutes. Used for busy-time collision detection — ensures wrap-up time is reserved.",
                verbose_name="Effective end (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="effective_start",
            field=models.DateTimeField(
                help_text="start_datetime minus buffer_before_minutes from the effective SchedulingPolicy. Used for busy-time collision detection — ensures back-to-back slots cannot overlap considering setup time.",
                verbose_name="Effective start (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="end_datetime",
            field=models.DateTimeField(
                db_index=True,
                help_text="Appointment end time in UTC. Must be after start_datetime.",
                verbose_name="End (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="internal_note",
            field=models.TextField(
                blank=True,
                help_text="Staff/admin notes about this slot. MUST NOT be shown to citizens or included in citizen-facing communications.",
                verbose_name="Internal note",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="is_walk_in_slot",
            field=models.BooleanField(
                default=False,
                help_text="If True, this slot is reserved for walk-in clients and does not appear in the advance booking flow. Used when appointment_type.allow_walk_in=True.",
                verbose_name="Walk-in slot",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="location",
            field=models.ForeignKey(
                help_text="Physical or virtual location where this appointment takes place.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="appointments.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional physical resource (meeting room, equipment) reserved for this slot. Used when the resource must be booked alongside the staff member.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="appointments.resource",
                verbose_name="Resource",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="spaces_used",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Count of confirmed bookings occupying this slot. Incremented by create_booking(); decremented by cancel_booking(). Always ≤ capacity (enforced by DB CheckConstraint). Updated with SELECT FOR UPDATE inside atomic() in the booking service.",
                verbose_name="Spaces used",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="staff",
            field=models.ForeignKey(
                help_text="The staff member assigned to conduct this appointment.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="appointments.staffprofile",
                verbose_name="Staff member",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="start_datetime",
            field=models.DateTimeField(
                db_index=True,
                help_text="Appointment start time in UTC. Convert to location.timezone for citizen-facing display.",
                verbose_name="Start (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("partial", "Partially Booked"),
                    ("full", "Fully Booked"),
                    ("blocked", "Blocked"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="available",
                help_text="Slot availability status. Transitions: available→partial→full (as bookings are added); full/partial→available/partial (as bookings are cancelled); any→blocked (admin action); any→cancelled (admin action); any→completed (end-of-day batch for past slots).",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="video_join_url_citizen",
            field=models.URLField(
                blank=True,
                help_text="Pre-generated video conference join link for the citizen. SECURITY: NEVER include in unauthenticated email. Deliver only inside authenticated portal session. Wave 7+.",
                verbose_name="Citizen video join URL",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="video_join_url_staff",
            field=models.URLField(
                blank=True,
                help_text="Pre-generated host/moderator link for the staff member. SECURITY: NEVER expose this field in citizen-facing API responses, email templates, or public serializers. This URL grants host/moderator access to the video session. Wave 7+.",
                verbose_name="Staff video join URL",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="video_meeting_id",
            field=models.CharField(
                blank=True,
                help_text="Platform-specific meeting ID (e.g., Zoom meeting ID, Teams thread ID). Wave 7+.",
                max_length=200,
                verbose_name="Video meeting ID",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="video_provider",
            field=models.CharField(
                blank=True,
                help_text="Video platform for this slot: 'teams', 'zoom', 'jitsi'. Wave 7+.",
                max_length=20,
                verbose_name="Video provider",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="exception_date",
            field=models.DateField(
                db_index=True,
                help_text="Calendar date this exception applies to.",
                verbose_name="Exception date",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="exception_type",
            field=models.CharField(
                choices=[
                    ("holiday", "Public Holiday / Day Off"),
                    ("leave", "Sick / Personal Leave"),
                    ("override", "Override Hours"),
                    ("training", "Training / Conference"),
                ],
                help_text="holiday/leave/training → no slots generated for this date. override → slots generated using override_start_time / override_end_time.",
                max_length=20,
                verbose_name="Exception type",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="internal_note",
            field=models.CharField(
                blank=True,
                help_text="Staff/admin-facing note about this exception. MUST NOT be shown to citizens or included in any citizen-facing communication.",
                max_length=200,
                verbose_name="Internal note",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="override_end_time",
            field=models.TimeField(
                blank=True,
                help_text="Custom end time in the staff's location timezone. Must be after override_start_time. Only required when exception_type='override'.",
                null=True,
                verbose_name="Override end time",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="override_start_time",
            field=models.TimeField(
                blank=True,
                help_text="Custom start time in the staff's location timezone. Only required when exception_type='override'.",
                null=True,
                verbose_name="Override start time",
            ),
        ),
        migrations.AlterField(
            model_name="staffexception",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
