"""
Wave 3 — Booking Engine: Booking, Attendee, BookingAuditLog tables.

Handwritten migration (not generated by makemigrations) to satisfy explicit
naming requirements and maintain strict dependency ordering.

Dependencies:
  - appointments.0010_alter_slot_options_and_more  (Slot model exists)
  - contenttypes.0002_remove_content_type_name     (GenericRelation infra)
  - auth_extension.0001_initial                    (AUTH_USER_MODEL)
  - documents.0001_initial                         (DocumentAttachment exists)
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("appointments", "0010_alter_slot_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth_extension", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        # ------------------------------------------------------------------
        # Booking
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Staff Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "no_show",
                    models.BooleanField(
                        default=False,
                        help_text="Staff marks True if client did not attend. NOT a status value.",
                        verbose_name="No-show",
                    ),
                ),
                (
                    "rescheduled",
                    models.BooleanField(
                        default=False,
                        help_text="True if this booking was replaced by a newer rescheduled booking.",
                        verbose_name="Rescheduled",
                    ),
                ),
                (
                    "reschedule_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="Reschedule count",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Cancelled at",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Cancellation reason"),
                ),
                (
                    "late_cancellation",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "True if cancelled within the cancellation_notice_hours window. "
                            "Used for no-show policy escalation."
                        ),
                        verbose_name="Late cancellation",
                    ),
                ),
                (
                    "booking_channel",
                    models.CharField(
                        choices=[
                            ("online", "Online Self-Service"),
                            ("phone", "Phone (Staff-Assisted)"),
                            ("walk_in", "Walk-In"),
                            ("staff_portal", "Staff Portal"),
                            ("api", "API"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Booking channel",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=5,
                        verbose_name="Language",
                    ),
                ),
                (
                    "appointment_mode",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("virtual", "Virtual (Video)"),
                            ("phone", "Phone"),
                        ],
                        default="in_person",
                        max_length=20,
                        verbose_name="Appointment mode",
                    ),
                ),
                (
                    "form_responses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Intake form answers. May contain Protected B data — access gated by permission.",
                        verbose_name="Form responses",
                    ),
                ),
                (
                    "interpreter_needed",
                    models.BooleanField(default=False, verbose_name="Interpreter needed"),
                ),
                (
                    "interpreter_language",
                    models.CharField(
                        blank=True,
                        help_text="Quebec Law 25: sensitive personal information — express consent required.",
                        max_length=50,
                        verbose_name="Interpreter language",
                    ),
                ),
                (
                    "accessibility_needs",
                    models.TextField(
                        blank=True,
                        help_text="Quebec Law 25: sensitive personal information — express consent required.",
                        verbose_name="Accessibility needs",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff/admin notes. MUST NOT be shown to citizens.",
                        verbose_name="Internal notes",
                    ),
                ),
                (
                    "confirmation_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Confirmation sent at",
                    ),
                ),
                (
                    "reminder_72h_sent",
                    models.BooleanField(default=False, verbose_name="72h reminder sent"),
                ),
                (
                    "reminder_24h_sent",
                    models.BooleanField(default=False, verbose_name="24h reminder sent"),
                ),
                (
                    "reminder_2h_sent",
                    models.BooleanField(default=False, verbose_name="2h reminder sent"),
                ),
                (
                    "reminder_72h_task_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="72h reminder task ID",
                    ),
                ),
                (
                    "reminder_24h_task_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="24h reminder task ID",
                    ),
                ),
                (
                    "reminder_2h_task_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="2h reminder task ID",
                    ),
                ),
                (
                    "work_item_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the related WorkItem (apps.workflows). Plain UUID, not FK.",
                        null=True,
                        verbose_name="Work item ID",
                    ),
                ),
                (
                    "service_request_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="Service request ID",
                    ),
                ),
                (
                    "consent_recorded_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Consent recorded at",
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Consent version",
                    ),
                ),
                # ForeignKeys
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="appointments.slot",
                        verbose_name="Slot",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Citizen",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled by",
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original booking this was rescheduled from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to_set",
                        to="appointments.booking",
                        verbose_name="Rescheduled from",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_booking_form_responses",
                        "Can view booking intake form responses (Protected B gate)",
                    ),
                    ("manage_no_shows", "Can manage citizen no-show records"),
                    (
                        "view_internal_notes",
                        "Can view staff-only internal booking notes",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["citizen", "status"],
                name="appt_booking_citizen_status",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["slot", "status"],
                name="appt_booking_slot_status",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "no_show"],
                name="appt_booking_status_noshow",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["citizen", "created_at"],
                name="appt_booking_citizen_created",
            ),
        ),
        # ------------------------------------------------------------------
        # Attendee
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("family_member", "Family Member"),
                            ("legal_guardian", "Legal Guardian"),
                            ("support_person", "Support Person"),
                            ("interpreter", "Interpreter"),
                            ("advocate", "Advocate / Representative"),
                            ("other", "Other"),
                        ],
                        default="family_member",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "no_show",
                    models.BooleanField(default=False, verbose_name="No-show"),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, max_length=64, verbose_name="Timezone"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        verbose_name="Preferred language",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="appointments.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee",
                "verbose_name_plural": "Attendees",
                "ordering": ["name"],
            },
        ),
        # ------------------------------------------------------------------
        # BookingAuditLog
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="BookingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Booking Created"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled_citizen", "Cancelled by Citizen"),
                            ("cancelled_staff", "Cancelled by Staff"),
                            ("cancelled_system", "Cancelled by System"),
                            ("rescheduled", "Rescheduled"),
                            ("completed", "Completed"),
                            ("no_show_marked", "No Show Marked"),
                            ("reminder_sent", "Reminder Sent"),
                            ("waitlist_joined", "Joined Waitlist"),
                            ("waitlist_promoted", "Promoted from Waitlist"),
                            ("document_attached", "Document Attached"),
                            ("payment_received", "Payment Received"),
                            ("consent_recorded", "Consent Recorded"),
                            ("data_purged", "Data Purged"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        help_text="String pk of the acting user, or 'system'. NOT a FK (PII safety).",
                        max_length=50,
                        verbose_name="Actor ID",
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name="Actor IP",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Previous status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="New status",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context. MUST NOT contain PII — slugs and UUIDs only.",
                        verbose_name="Detail",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="appointments.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Audit Log Entry",
                "verbose_name_plural": "Booking Audit Log Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="bookingauditlog",
            index=models.Index(
                fields=["booking", "timestamp"],
                name="appt_bookingaudit_booking_ts",
            ),
        ),
    ]
