# Generated by Django 5.2.3 on 2026-06-29 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "channel", "read_at"], name="notificatio_recipie_777071_idx"
            ),
        ),
    ]
